### ISSUE TITLE
Allow global job definitions

### ISSUE THREAD

**Issue by d12bb** [Canop/bacon#101]
Would be great if bacon could honour job definitions from `prefs.toml`, if not overridden by the local `bacon.toml`. This could be used to set flags one is always using, or adding another test framework like nextest, which is drop-in / not project-specific.

**Comment by Canop** [comment]
I'll probably do that but I'm a little worried that such global jobs wouldn't usually be shared between people working on a repository.

**Comment by d12bb** [comment]
That's obviously correct, but I think not all jobs need to. To keep with my example, if I just prefer the output format of Nextest, I can set it as test job globally, without affecting anyone else working on the same codebase, who might not even have it installed. If a project relies on some special flags or another, incompatible test runner, the test job will be overridden in the repo, so the global job does no harm there either.

**Comment by Stargateur** [comment]
the problem is generally inverse, people config their global then complain it doesn't work cause it has been override by local config. However I think this is a nice feature to have.

**Comment by Canop** [comment]
I decided for something very simple: allow exactly the same settings in both files.

Can you please check the PR ?

https://github.com/Canop/bacon/pull/102

**Comment by Canop** [comment]
There could also be a `bacon-personal.toml` file for the local and personal stuff overriding the bacon.toml file.
Not sure there's really a need, though.

**Comment by d12bb** [comment]
> I decided for something very simple: allow exactly the same settings in both files.
> 
> Can you please check the PR ?
> 
> #102

Nice, works exactly as I wanted!

**Comment by Canop** [comment]
Feature available in bacon 2.4.0
