### ISSUE TITLE
[Feature request] key shortcut to force a re-run

### ISSUE THREAD

**Issue by danielhenrymantilla** [Canop/bacon#105]
Hey, big user of your excellent pragmatic tool here 😄 

One thing that sometimes happens, is that `bacon` `watch` heuristics may not be 100% accurate with the real file-dependency involved in a complex project (_e.g._, imagine a `build.rs` depending on some weirdly-located file, or perhaps more realistically, a project depending on another one located at some other folder).

In that case, when I (hopefully rarely) update a file unbeknownst to `bacon`, **I have to explicitly press `q` followed by `↑` and `↩`** to force a `bacon` rerun.

It would be awesome if, akin to `q`, **we had some shortcut to trigger a rerun of the registered command**. Thanks! 🙏

**Comment by danielhenrymantilla** [comment]
[Wow what a prompt reply!] If you point me to the relevant file, I can even try to submit a PR myself, btw

**Comment by Canop** [comment]
There's no reason for a feature gate here: An [internal](https://dystroy.org/bacon/config/#internals), when it's not bound to a key shortcut, has no downside.

If you don't mind, I prefer to do this specific change myself.

**Comment by Canop** [comment]
@danielhenrymantilla Can you test https://github.com/Canop/bacon/pull/106 ?

**Comment by Canop** [comment]
This is part of bacon 2.5.0 that I just released.
