### ISSUE TITLE
Clarify usage on clippy args (plz)

### ISSUE THREAD

**Issue by dj8yfo** [Canop/bacon#107]
How does one run? 
```
bacon clippy  -- -D warnings -A clippy::derive-partial-eq-without-eq
```

**Comment by dj8yfo** [comment]
```
error: Found argument '-D' which wasn't expected, or isn't valid in this context
                                                                                                                                                                                             
    If you tried to supply `-D` as a value rather than a flag, use `-- -D`
```

**Comment by Canop** [comment]
It's easier to just put them in the bacon.toml file: https://dystroy.org/bacon/cookbook/#configure-clippy-lints

If you don't want to have such configuration, then you must double the double dash:

    bacon clippy  -- -- -D warnings -A clippy::derive-partial-eq-without-eq

**Comment by Canop** [comment]
Other example: the bacon.toml file of the bacon project: https://github.com/Canop/bacon/blob/main/bacon.toml#L15

**Comment by Stargateur** [comment]
double² dash ?

**Comment by Canop** [comment]
That's the problem when you have programs (ie bacon) wrapping programs (ie cargo) wrapping programs (ie clippy)

I've even had the case of a triple double dash with another program wrapping cargo test with the tested thing needing args...

**Comment by dj8yfo** [comment]
Thx!
