### ISSUE TITLE
Every command fails when offline because of cargo metadata

### ISSUE THREAD

**Issue by ariofrio** [Canop/bacon#110]
I tried running bacon when I didn’t have Internet connection and found that every command, even `--init`, failed when it tried to run `cargo metadata`.

```
Error: `cargo metadata` exited with an error:  Downloading crates ...
warning: spurious network error (2 tries remaining): [6] Couldn't resolve host name (Could not resolve host: crates.io)
```

I’ve been taking a look at [the relevant source code](https://github.com/Canop/bacon/blob/3e56b933daec7ca70b8c7e42e5c7cba49d498eda/src/mission_location.rs#L7) and [documentation](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#manifest-options). Seems like we could pass `--frozen` to avoid network requests. Not sure if bacon need an up to date dependency graph or to detect if dependencies are out of date to function? If not, we could be using bacon offline. Airplane and beachside coding FTW!

For reference, cargo run, cargo clippy, cargo check, cargo test etc generally work offline as long as you don’t add a new dependency. Cargo add generally doesn’t work offline, though sometimes adding —offline will do the trick by using the local crates cache.

**Comment by Canop** [comment]
I should be available to pass the `--offline` option with [other_options](https://docs.rs/cargo_metadata/latest/cargo_metadata/struct.MetadataCommand.html#method.other_options) [here](https://github.com/Canop/bacon/blob/main/src/mission_location.rs#L45).

I'll test when I find the time (hint: you can try too).

**Comment by ariofrio** [comment]
I tried passing CARGO_NET_OFFLINE env var and it failed. I think it might be necessary to use frozen instead of offline. Will try it out. 

Does the approach make sense though? Skimming through the bacon code it doesn’t seem that it’ll be a problem not to check for outdated dependencies, but just want to make sure I didn’t miss anything.

**Comment by Canop** [comment]
Bacon uses `cargo metadata` (through [the cargo_metadata crate](https://docs.rs/cargo_metadata/latest/cargo_metadata/index.html)) to get
- the root Cargo.toml file
- the list of all packages sources

Those paths are necessary because bacon will watch them. And they're not always trivial to find.

Unfortunately there doesn't seem to be an option to do only the resolution which can be done without fetching dependencies over the net.

**Comment by ariofrio** [comment]
Adding `--offline` to the cargo metadata call yields the error:

```
Error: `cargo metadata` exited with an error: error: failed to download `bumpalo v3.11.1`

Caused by:
  attempting to make an HTTP request, but --offline was specified
```

Adding `--frozen` fails with a similar error:

```
Error: `cargo metadata` exited with an error: error: failed to download `bumpalo v3.11.1`

Caused by:
  attempting to make an HTTP request, but --frozen was specified
```

I found [this `cargo metadata` issue about working offline](https://github.com/rust-lang/cargo/issues/9273). @ehuss suggested using "`--filter-platform` to only show metadata for a specific platform that has been downloaded." Would that be an acceptable solution for bacon?

From [the documentation](https://doc.rust-lang.org/cargo/commands/cargo-metadata.html#output-options):

> `--filter-platform` _triple_
>
> This filters the `resolve` output to only include dependencies for the given target triple. Without this flag, the resolve includes all targets.
>
> Note that the dependencies listed in the "packages" array still includes all dependencies. Each package definition is intended to be an unaltered reproduction of the information within `Cargo.toml`.

I tried it with my default platform returned by `rustc -vV` (`--filter-platform=aarch64-apple-darwin`) and that made bacon work offline.

**Comment by Canop** [comment]
`--filter-platform` shouldn't cover all the cases, especially when you're missing  dependencies.

I'm testing another approach.

**Comment by Canop** [comment]
@ariofrio Can you test this PR ? https://github.com/Canop/bacon/pull/111
