### ISSUE TITLE
Bacon eats clippy warnings

### ISSUE THREAD

**Issue by sylbeth** [Canop/bacon#115]
It seems like every time I try to run clippy, bacon just eats the output I want to see.

![image](https://user-images.githubusercontent.com/102521501/220811774-c404949e-2c75-4469-91dc-55a4f4c6416e.png)

vs

![image](https://user-images.githubusercontent.com/102521501/220811831-e64ca5f7-485b-4f4a-8ed5-f05bbeb48f04.png)

is there a reason for it? A way for enabling it to show everything? A key to press? I can't find anything on it so that's why I'm asking.

**Comment by sylbeth** [comment]
It's a duplicate, same as the one about the Windows Terminals. I'll move there, sorry for not finding it sooner.

**Comment by Canop** [comment]
> sorry for not finding it sooner

No worry. Thanks for finding it.

Closing as duplicate.
