### ISSUE TITLE
Bacon doesn't play well with the new `sparse` protocol

### ISSUE THREAD

**Issue by HollayHorvath** [Canop/bacon#118]
With the new sparse protocol enabled on `~/.cargo/config.toml`, `bacon` doesn't show any output while dependencies are being downloaded. Since this step could take a while and doesn't use much CPU, the user can think that `bacon` is stuck (well, at least I run into this after the 1.68 release today).

Repro is simple:
```Bash
cargo new bacon_seems_stuck
cd bacon_seems_stuck
cargo add aws-sdk-s3 # doesn't really matter, but should be a big crate that you don't have cached locally
bacon check
```

**Comment by Stargateur** [comment]
is normal cargo behavior show nothing too ?

**Comment by HollayHorvath** [comment]
> is normal cargo behavior show nothing too ?

Cargo shows a simple loadbar during this operation

**Comment by Stargateur** [comment]
this mean cargo is using curse api, I think you should get this issue to cargo, bacon should do anything.
