### ISSUE TITLE
Watch all paths?

### ISSUE THREAD

**Issue by max-sixty** [Canop/bacon#119]
In https://github.com/PRQL/prql/pull/2091, I'm spamming `watch = ["tests", "benches", "examples"]`.

Would it be reasonable to have the default be all non-gitignored paths, and then allow folks to specify a smaller set of paths? Or allow `*`? Or allow a default for the whole file?

(to clarify, it already excludes `.gitignore`, so we don't need to worry about `target` etc)

**Comment by Canop** [comment]
*waiting for other opinions*

**Comment by Stargateur** [comment]
I'm think follow cargo package layout is a better idea than watch all directory, https://doc.rust-lang.org/cargo/guide/project-layout.html:

* `Cargo.toml` and `Cargo.lock` are stored in the root of your package (*package
  root*).
* Source code goes in the `src` directory.
* The default library file is `src/lib.rs`.
* The default executable file is `src/main.rs`.
    * Other executables can be placed in `src/bin/`.
* Benchmarks go in the `benches` directory.
* Examples go in the `examples` directory.
* Integration tests go in the `tests` directory.

So I think there is no need to do more, basically watch should "by default" wait "cargo" nomenclature so "watch = ["tests", "benches", "examples"]" is already enough.

I have no opinion on this except this remark. So neutral.

**Comment by max-sixty** [comment]
> So I think there is no need to do more, basically watch should "by default" wait "cargo" nomenclature so "watch = ["src", "tests", "benches", "examples"]" is already enough.

Yes, plus the Cargo files. And for every crate in the workspace. I agree that has as much functionality as "everything". though seems much more work to do!

**Comment by Cthutu** [comment]
I agree about this.  Currently, I prefer `cargo-watch` because it will retrigger when I save a file in a crate in my workspace.  With bacon, I have to constantly press `F5` to recompile my main package after I change a dependency carate.

**Comment by Canop** [comment]
I don't get the problem you have. I never have to do F5 whatever my workspace. Can you build a test project exhibiting this problem ?

**Comment by Cthutu** [comment]
Yes, it's easy to reproduce one of the problems I am having:
```rust
// src/lib.rs:
pub fn greet(name: &str) {
    println!("Hello {name}");
}


// examples/world.rs:
use t::greet;

fn main() {
    greet("World");
}
```

Run `bacon run -- --example world` and you will see `Hello World` as expected.  Now change `World` to something else and save `world.rs`.  Bacon will not rebuild.

I think this also happens with crates within the same directory.  For example, imagine adding a dependency:
```
"foo": { path = "../crates/foo" }
```

Changing any files there will not cause a rebuild.

**Comment by Canop** [comment]
Ok @Cthutu , I see, I hadn't understood your meaning at first.

Right now I think like @Stargateur that having `watch = ["src", "tests", "benches", "examples"]` by default would be the best solution.

Side note: it's possible to change your jobs with `watch = ["."]` (jobs wouldn't be triggered on gitignored files).

**Comment by Canop** [comment]
tests of https://github.com/Canop/bacon/pull/121 welcome

**Comment by max-sixty** [comment]
Thanks @Canop !
