### ISSUE TITLE
bacon test doesn't color tests

### ISSUE THREAD

**Issue by svenstaro** [Canop/bacon#124]
Hey, cool project! This is kind of a minor issue but I still think it'd be nice to have tests be able to output in color. However, `bacon test` doesn't use color unless forced to with `bacon test -- -- --color always` which is kind of inconvenient.

There is this related issue: https://github.com/rust-lang/cargo/issues/1983

**Comment by Canop** [comment]
Can you build a test case exhibiting the lack of color ?

**Comment by svenstaro** [comment]
Result of `bacon test` on a random Rust project with tests:

![image](https://user-images.githubusercontent.com/1664/227705644-229c6ba6-7181-4159-ad6e-c2c5c2c71ffc.png)

Running it with `bacon test -- -- --color always`:
![image](https://user-images.githubusercontent.com/1664/227705690-74ab9690-332b-4ff6-a856-e3b5de569695.png)

**Comment by Canop** [comment]
Ok, I see.

So this could be fixed with this definition of the test job (wich I could make default):

```
[jobs.test]
command = ["cargo", "test", "--color", "always", "--", "--color", "always"]
need_stdout = true
```

Any better suggestion ?

**Comment by svenstaro** [comment]
I think that'd work. Since bacon is only ever meant to run interactively, I don't see any issues here.
