### ISSUE TITLE
Screen doesn't clear when running on quiet mode

### ISSUE THREAD

**Issue by ajitid** [Canop/bacon#131]
Here's what I did:

1. Fill prefs.toml with:

```toml
default_job = "clippy"

[jobs.clippy]
command = [
    "cargo", "clippy",
    "--quiet",
    "--all-targets",
    "--color", "always",
]
need_stdout = false
```
2. Create a new project with cargo new and replace main.rs content with

```rs
fn main() {
    let _x = 1;
}
```
3. Create an empty `bacon.toml` in project root. Then run bacon 
4. There would be no output to show so the clippy job would output nothing
5. Now change `_x` var to `x` and save the file. This will show a warning. Now change `x` back to `_x` and save the file again. While there no warning actually by clippy, bacon doesn't clears its output.

All in all, if the output content changes from some text to empty, bacon doesn't update its output in this case.

**Comment by Canop** [comment]
Why do you want to run cargo with --quiet in bacon ?

**Comment by ajitid** [comment]
Because of preference. As I am learning Rust, I created two terminal panes, one for output, and another for errors via clippy. I just want to see nothing if there's no error, but clippy outputs

```
 Finished dev [unoptimized + debuginfo] target(s) in 0.09s
```

in this case. I'd prefer that pane to be blank.

Even if this case is not considered for a fix, I still think showing stale output in general would not be right.

**Comment by Canop** [comment]
You mean you're trying to remove the two lines of text here ?
![image](https://user-images.githubusercontent.com/617006/233848886-2e4f674f-9284-428e-ac05-9e89dd3db0a7.png)

**Comment by ajitid** [comment]
Yes
