### ISSUE TITLE
nexttest in bacon won't scroll output

### ISSUE THREAD

**Issue by damccull** [Canop/bacon#133]
Trying to set up a bacon job for nextest but I can't get the output to be scrollable after it's done, so I can't see the result.

```
[jobs.nextest]
command = ["cargo", "nextest", "run", "--color", "always", "--hide-progress-bar", "--failure-output", "final"]
need_stdout = true
```

How can I fix this?

**Comment by miguno** [comment]
+1

Same situation and same problem here.

**Comment by ilyagr** [comment]
I tried @damccull 's snippet, and it worked for me. I haven't immediately observed any problems with scrolling.

Thank you for sharing the helpful snippet, I'm happy not to have to rediscover the necessity of each of those flags!

**Comment by miguno** [comment]
This can be resolved because https://github.com/Canop/bacon/issues/137 is resolved, too?

**Comment by Canop** [comment]
But #137 is resolved

**Comment by Canop** [comment]
Closing.

Note: there's another issue related to nextest (not quite the same), https://github.com/Canop/bacon/issues/196
