### ISSUE TITLE
Run Job doesn't clear .bacon-locations when no errors are present

### ISSUE THREAD

**Issue by ConnorWay32** [Canop/bacon#136]
Noticed that if I have Bacon on the `run` job on a file with errors, then it will correctly populate the .bacon-locations file with errors. However, when the errors are removed and the `run` job performed again, the error listing in the .bacon-locations file is not removed. As this is different behavior from the `check-all`, `clippy`, and `test` jobs, I'm assuming this is unintentional.

**Comment by Canop** [comment]
I don't reproduce that.
Is that perhaps because your `cargo run` execution fails or is long ?

**Comment by ConnorWay32** [comment]
I had tested it on small files with basic syntax errors, but it doesn't seem to be happening for me either anymore. I'll close the issue for now unless I find some specific conditions for it to occur.
