### ISSUE TITLE
[feature request] some binding to show quick summary of toolchain used for job

### ISSUE THREAD

**Issue by dj8yfo** [Canop/bacon#139]
it would be nice to have an additional binding `toggle toolchain info` or smth like that.
Just an idea though, not a hard requirement)

**Comment by dj8yfo** [comment]
```bash
rustc --version
rustup show active-toolchain # if rustup is available
```

**Comment by Canop** [comment]
Closing in favor of the most general https://github.com/Canop/bacon/issues/239
