### ISSUE TITLE
Add environment vars to config

### ISSUE THREAD

**Issue by joshka** [Canop/bacon#145]
I'm trying to run e.g.
```toml
command = [
    "RUSTDOCFLAGS=--cfg", "docsrs",
    "cargo", "+nightly", "doc",
    "--all-features",
    "--color", "always",
    "--no-deps",
    "--open"]
```
I'm using the doc_auto_cfg feature, which is only available in nightly, so have put that behind a flag (docsrs), but I'd like to test that locally and iterate on some of the other docs in the lib I'm working on.

Proposal:
```toml
environment.RUSTDOCFLAGS = "--cfg docsrs"
```

current workaround is I can set an environment variable specifically, but that effects all processes (alternatively use .direnv etc.)

**Comment by Canop** [comment]
This looks like a good idea, and simple to do.
I'll have a try.

**Comment by Canop** [comment]
@joshka Can you check https://github.com/Canop/bacon/pull/146 ?

**Comment by joshka** [comment]
Closing the loop in case anyone else is searching for how to configure that specific use case, here's what works for me:

```toml
[jobs.doc]
command = [
    "cargo", "+nightly", "doc",
    "-Zunstable-options", "-Zrustdoc-scrape-examples",
    "--all-features",
    "--color", "always",
    "--no-deps",
]
env.RUSTDOCFLAGS = "--cfg docsrs"
need_stdout = false

# If the doc compiles, then it opens in your browser and bacon switches
# to the previous job
[jobs.doc-open]
command = [
    "cargo", "+nightly", "doc",
    "-Zunstable-options", "-Zrustdoc-scrape-examples",
    "--all-features",
    "--color", "always",
    "--no-deps",
    "--open",
]
env.RUSTDOCFLAGS = "--cfg docsrs"
need_stdout = false
on_success = "job:doc" # so that we don't open the browser at each change
```
