### ISSUE TITLE
Showing only one error/warning per page

### ISSUE THREAD

**Issue by DottieDot** [Canop/bacon#148]
Hi, 

I was wondering if it's possible to only show one warning or error on a single page? 

Seeing them all at once can be a bit overwheling and it'd be nice to be able to view them one by one.

**Comment by Canop** [comment]
no, there's no such feature, sorry.

**Comment by Stargateur** [comment]
you can maybe use a pipe and `head` to limit size output.

**Comment by Canop** [comment]
I don't intend to add such feature.
