### ISSUE TITLE
Support compiler feature flags

### ISSUE THREAD

**Issue by timvisee** [Canop/bacon#15]
It would be awesome if `bacon` could support compiler feature flags. Namely `--features <FEATURES>...` and `--no-default-features.

```bash
$ cargo build --help | grep feature
        --features <FEATURES>...     Space or comma separated list of features to activate
        --all-features               Activate all available features
        --no-default-features        Do not activate the `default` feature
```

I'm not sure how `bacon` calls the Rust compiler. If it's invoking the `cargo` command on your system, you might add a flag or environment variable to modify the command it uses as well. That might be easier to implement, and does support setting feature flags as well.

**Comment by Canop** [comment]
This is in project. It's hinted in https://github.com/Canop/bacon/issues/9

**Comment by timvisee** [comment]
Awesome, didn't notice.

Because I thought this would be a minor change I also implemented it myself just now:

- Commit: https://github.com/timvisee/bacon/commit/a23ef5a69bfbd4e07a83f357af9315645f642dc3
- MR: https://github.com/Canop/bacon/compare/main...timvisee:feature-flags?expand=1

Feel free to merge it if it comes to use.
