### ISSUE TITLE
Using `bacon` with `rust-analyzer` in VS Code

### ISSUE THREAD

**Issue by bzm3r** [Canop/bacon#158]
I'm interested in using `bacon` with `rust-analyzer`.

`rust-analyzer` allows for [compiler feedback from external tools](https://rust-analyzer.github.io/manual.html#compiler-feedback-from-external-commands).

In VS Code, we must define a build task, I think something like this under the project's `.vscode/tasks.json`:

```rust
{
    "label": "Watch",
    "group": "build",
    "type": "shell",
    "command": "bacon",
    "problemMatcher": "$rustc-watch",
    "isBackground": false
}
```

However, the part I am uncertain about is how to set up my `bacon.toml` so that the cargo check/clippy command emits errors out in json to stderr using the flag [`--error-format=json`](https://doc.rust-lang.org/rustc/json.html). 

If I set up a command like this:

```rust
[jobs.clippy]
command = [
    "cargo",
    "clippy",
    "--all-targets",
    "--color",
    "always",
    "--",
    "--error-format=json"
]
need_stdout = false
```
Then I get a build error stating that I provided the error-format argument twice. 

Is this due to a clash with the [`-e` option of `bacon`](https://dystroy.org/bacon/config/#export-locations)? I have disabled this in `prefs.toml` both by trying `enabled = false` and simply commenting out the entire block, with no success. 

Any ideas on what I can try next? Is there a way for me to pass the default `.bacon-locations` (perhaps I have to rename the output file) to rust-analyzer? Not entirely sure, so all ideas would be appreciated!

**Comment by Canop** [comment]
This isn't clear to me.
You'd like bacon to not display the errors itself but to send to vscode the raw JSON output of cargo ?

**Comment by Canop** [comment]
Right now bacon uses stdout for its output, so a solution could be to send to stderr what it receives, assuming vscode accepts it.
But there's no such feature in bacon, it would need to be added. Or maybe use a tee as job.

**Comment by Niraj-Kamdar** [comment]
@bzm3r I am interested in your current setup, Rust-Analyzer is too slow for our gigantic repo, I would prefer if I can just use RA for code navigation and code hinting while use slow running background checks for errors and lazily see those

**Comment by bbb651** [comment]
In case you're unware, there's a project that implement a language server backed by bacon: https://github.com/crisidev/bacon-ls

**Comment by Canop** [comment]
With the current export framework, this could be implemented with just a "raw-output" export, but I'll only implement it if there's some demand. See https://github.com/Canop/bacon/issues/240

**Comment by davehorner** [comment]
Thought I would add that I've been using vscode workspace open via cli to get the analyzer time to work and then code opens the files and moves to the line positions great. https://github.com/davehorner/cbacon

**Comment by Canop** [comment]
Why the "cbacon" name ?

And what about adding an item in the Community button of the bacon site ?

**Comment by davehorner** [comment]
code is the name of the program i'm executing to run vscode, if you look at the python scripts it started as vscode_ i think.  code bacon or see bacon. i thought it worked but question its value in itself.

yes, if you'd like to go the way of inclusion in the community site as another way to keep an editor in sync with bacon we can do that.

I'm happy to call it whatever, I'd like to see it not be needed and contribute the code to make this happen in bacon itself. or not be bacon specific.

I mentioned that I would really like to contribute or suggest the ability to press the number of the warning or error and again call into vscode via workspace open, file open.  I understand the core purpose is to have you in the editor and moving to the issues.  

pressing the number to get to the line in nvim/vscode without the need for a vim config or another process that you need to clean up would be nice.  vscode has some good handling of multiple executions...not causing many clients and referencing the same vscode.

I'm not ready to release the rust client yet.  if you want to keep it separated and on the community site I will polish it.  I do not like that you can start multiple cbacon processes, there's already 1 long running bacon process and now Ive to to make sure I dont pollute the system with many unwanted processes.  this is all just a spawn with the proper arguments away, no need for a cbacon or a vim plug.  there's other things I would do before calling it a public.

**Comment by Canop** [comment]
> pressing the number to get to the line in nvim/vscode without the need for a vim config or another process that you need to clean up would be nice

Yes. I must find time to work on this.
