### ISSUE TITLE
Screen doesn't clear when the file watcher restarts a long-running job

### ISSUE THREAD

**Issue by Jayshua** [Canop/bacon#159]
When using the "Run" job with a long-running or never exiting project like a web server, the screen fails to clear when the file watcher triggers a rebuild.

To reproduce:
- Use the "Run" job on a project that doesn't exit when it is run.
- Introduce an error so that the build fails, noting the error in the bacon console.
- Fix the error.
- Note that bacon gets the "computing..." flag, but the output screen continues to show the old error message even though the build was successful and running.
- Force a re-run with the "r" key and note that the screen is now cleared and shows the project output.

I would have expected to see the output of the running project after the file watcher automatically triggers a rebuild.

I was able to fix this issue with the following patch. If this is a fix you'd like I could submit a pull request.

```patch
diff --git a/src/app.rs b/src/app.rs
index 7d10b3d..64e3e7a 100644
--- a/src/app.rs
+++ b/src/app.rs
@@ -104,6 +104,7 @@ pub fn run(
                     debug!("error sending task: {}", e);
                 } else {
                     state.computation_starts();
+                    state.cmd_result = CommandResult::None;
                 }
             }
             recv(executor.line_receiver) -> info => {
```

**Comment by Jayshua** [comment]
After continuing to use bacon I noticed that, while it does clear the output when re-running after a failed build, it appends the output of multiple successful builds rather than clearing the entire screen for each build. I fixed that by adding this line just above the new line in the patch above:

```rust
state.take_output();
```

**Comment by Canop** [comment]
Thanks for the detailed report.

This isn't the right solution: we don't want to clear the output on start of computation, we want to keep it during long compilations for example.

I'll look deeper into this.

**Comment by Canop** [comment]
I'm currently envisioning 2 changes to solve that:
1. reset the output on F5
2. try to detect in stdout+stderr when the compilation ends and when the "Running" starts, then switch the output at this point

If I can't make 2 work reliably, I could add a "never-ending" optional flag for jobs: this would imply that the switch to the new output would be done on execution start instead of execution end.

**Comment by Jayshua** [comment]
Personally I'd prefer the config flag.

I like seeing bacon pick up the change immediately by clearing the screen, and sounds from the way you described option 2 that it wouldn't clear the output until the build completes and execution begins.

If you do go down the config route, I'd suggest something like "clear-on-rerun" or "rerun-output-behavior=clear" rather than "long-running" since that feels clearer to me personally. It would also let you add an option for "append" if that were a feature you were interested in.

**Comment by Canop** [comment]
> sounds from the way you described option 2 that it wouldn't clear the output until the build completes and execution begins.

IMO this is ideal: rather than have nothing usable on screen, you still have the previous output (either errors to solve or compiled program's output) until there's something useful to display.

> If you do go down the config route, I'd suggest something like "clear-on-rerun" or "rerun-output-behavior=clear"

It's not about whether to clear, but *when*: part of bacon's point is to do the compilations in background so that you can keep working while there's a compilation, which is especially important when your program isn't trivial anymore and takes several seconds or minutes to compile.

**Comment by Jayshua** [comment]
That makes sense. It just isn't my workflow personally. I go to a lot of effort to keep compilation time short enough for rapid edit-test cycles - using a faster linker instead of ld, avoiding extensive macros and build scripts, using position-dependent output to avoid generating relocation segments in the executable (although I'm not sure that one actually helps all that much), etc. It's more useful to me to have bacon surface additional context to me as rapidly as possible than it is to overlap builds with further edits.

Whatever makes sense to you 👍. I can just keep using my two-line patch easily enough.

**Comment by Canop** [comment]
I named the setting `background=false` :  it describes precisely what it does. See https://github.com/Canop/bacon/pull/161

**Comment by Jayshua** [comment]
> Tests would be welcome.

I tried the background-optional branch (3637c3c803cadcd1f2733ecce42d98ccb652fed5), it seems to work as intended when setting background=false on bacon.toml. Thanks!
