### ISSUE TITLE
run tests with `-- --nocapture` option

### ISSUE THREAD

**Issue by anupj** [Canop/bacon#162]
Sometimes I'd like to see `println!` statements when I run my tests for "advanced" debugging. Is this possible using bacon?

**Comment by Canop** [comment]
You can change the "test" job in your bacon.toml file to

```
[jobs.test]
command = ["cargo", "test", "--color", "always", "--", "--nocapture"]
need_stdout = true
```

But honestly, it's simpler to just have the test fail by adding a `todo!()` : this way you only have one test clutter the output.

**Comment by anupj** [comment]
Thank you @Canop 
Could you elaborate this bit please?
> But honestly, it's simpler to just have the test fail by adding a todo!() : this way you only have one test clutter the output and you don't have to change job or restart bacon.

Do you mean adding a `todo!()` to the test method?

**Comment by Canop** [comment]
> Do you mean adding a todo!() to the test method?

Yes, at the end. When a test fails, the captured output is dumped and is thus displayed in bacon (same when using `cargo test`).
