### ISSUE TITLE
Fails to build with nightly 98aa3624b 2024-02-08 in ahash-0.8.2

### ISSUE THREAD

**Issue by mbuesch** [Canop/bacon#168]
bacon fails to build with nightly:

```
error[E0635]: unknown feature `stdsimd`
  --> /.../rust-nightly/cargo/registry/src/index.crates.io-6f17d22bba15001f/ahash-0.8.2/src/lib.rs:99:42
   |
99 | #![cfg_attr(feature = "stdsimd", feature(stdsimd))]
   |                                          ^^^^^^^
```

Note that ahash-0.8.2 is yanked.

**Comment by Canop** [comment]
At first sight it looks like it would be enough to have this in the dependencies:

```
ahash = "0.8.7"
gix = "0.40"
```

but it's probably possible to try having a more recent version of gix, this will need some work.

**Comment by mbuesch** [comment]
I also tried with running `cargo update` first, but than it fails at a different place for a different reason.
So currently --locked and not--locked fails on nightly.

**Comment by Canop** [comment]
@mbuesch Tests of the PR would be welcome.

**Comment by mbuesch** [comment]
I confirm that branch 57719f12fb5606386e18ed0865627be913382a59 fixes the build issue.
Thanks a lot for your quick help :)
