### ISSUE TITLE
Bacon fails to properly rerun on changes that happen while compilation is ongoing

### ISSUE THREAD

**Issue by GeeWee** [Canop/bacon#170]
Split off from #163 

bacon seems to get "stuck" if it compiles something with an error, and the error has been fixed before the compilation is done. It does not always rerun the compilation. E.g. see the [following loom ](https://www.loom.com/share/d52c52721f0043e49301dc76c3b78bd7) to demonstrate the problem, where you can see that the first time, bacon performs the recompilation successfully, but not the second time (15s in approx).

I've tried to replicate the same problem with cargo-watch which seems to handle this case successfully. See [this loom](https://www.loom.com/share/dfdcbe2b69de4b4aa0e5c7be9eed9fc0) as an example.

**Comment by Canop** [comment]
To ease analysis: can you reproduce the problem with the [no-async branch](https://github.com/Canop/bacon/pull/164) ?

Please edit your post with the editor and OS as it's certainly related to the way they save the file.

**Comment by GeeWee** [comment]
For sure. I've just tried with the no-async-branch and originally the behaviour seems to be the same, however after restarting my shell I'm not longer able to reproduce after switching the branch. So it might have resolved itself with the new executor!

**Comment by GeeWee** [comment]
After running the `no-async-branch` for a while the problem doesn't seem to occur, in that it doesn't fail to compile. It does however flicker a lot with results - my theory is that it still does racy work in parallel or similar in the background when many file updates happen quickly.

**Comment by Canop** [comment]
The no-async branch has been merged to main, and some changes happened since. Do you reproduce the flickering problem with current main ?

**Comment by GeeWee** [comment]
Just tried re-running main. I don't see the flickering anymore, but the original issue has resurfaced :(

**Comment by Canop** [comment]
I managed to make it happen a few times, but not in reproducible way :\

**Comment by GeeWee** [comment]
Yeah me neither :( - but glad that it's not just my computer being wonky!

**Comment by Canop** [comment]
I think this has been solved with the 3.0.

Please reopen if I'm wrong.
