### ISSUE TITLE
Can't seem to make `bacon test --no-default-features` work

### ISSUE THREAD

**Issue by Scripter17** [Canop/bacon#172]
Bacon version: 2.14.2

OS: Kubuntu 23.10

Rustc: 1.76.0

---

Steps to reproduce:

1. `cargo new abcd`
2. `cd abcd`
3. `bacon test --no-default-features`: Asks to be rerun with `--bin abcd`
4. `bacon test --no-default-features --bin abcd`: Doesn't even parse the arguments
5. `bacon test --no-default-features -- --bin abcd`: Same as 3
6. `bacon test -- --no-default-features`: Same as 3
7. `bacon test -- --no-default-features --bin abcd`: Same as 3

`bacon clippy --no-default-features` works perfectly fine

**Comment by Canop** [comment]
This was just fixed in main: https://github.com/Canop/bacon/issues/171

I should release a new version before the end of the week.

**Comment by Scripter17** [comment]
Confirmed working. Thank you so much!
