### ISSUE TITLE
Not displaying correctly on Windows Terminal, offset by one line

### ISSUE THREAD

**Issue by OwenJPage** [Canop/bacon#175]
When running Bacon from Windows Terminal, the display is vertically offset by a single line such that the top bar is not visible while the shortcut legend at the bottom occupies two lines.

Top bar will appear for a split second when scrolling, but will then disappear again. Display will adjust to window resizing as normal but will retain the vertical offset.

![image](https://github.com/Canop/bacon/assets/29840600/b15399a6-41a7-46cc-8902-f49a510d9291)

**Comment by Canop** [comment]
Can you please check whether the bug disappears with https://github.com/Canop/bacon/pull/176 ?

(I don't have any Windows computer available to test myself)

**Comment by Canop** [comment]
Just to be sure: with the PR, bacon is fully displayed from top to bottom, like this ?
![image](https://github.com/Canop/bacon/assets/617006/cd0063a3-757f-4040-8ce2-ed57a9b3565d)

**Comment by OwenJPage** [comment]
Works correctly on legacy windows terminal too.
![image](https://github.com/Canop/bacon/assets/29840600/491b0d5f-12b1-4375-b3c9-a3b6a17a82b4)

Have come across some other weird behaviour which I'll create a new issue for.
