### ISSUE TITLE
Decide what files & folders to watch, where to run Cargo.toml

### ISSUE THREAD

**Issue by Canop** [Canop/bacon#18]
Discussions and even [a PR](https://github.com/Canop/bacon/pull/14/files) have already occurred on this topic with @nikhilmitrax and @jyn514 but I'd like to decide on a specification before going further.

# Goals

* allow watching only parts of the source, to prevent inotify from using excessive resources on huge repositories
* being compatible with workspaces
* not be painful to launch or configure

# Proposal

* I call `intended directory`:
  * the closest directory of the path given as argument or if none
  * the current directory
* the `package directory` is the closest one from the intended one containing a `Cargo.toml` file
* the `Cargo.toml` file is watched by notify
* we also watch with notify
  * the `intended directory` if given explicitly or
  * the source directories given by the Cargo.toml file (using the cargo_metadata crate)
* `cargo check` (or other commands, see other issues) is launched in the `package directory`

(edited)

**Comment by jyn514** [comment]
I think the terminology is a little confusing, I'd suggest
- `source directory` for what you currently call `target directory`, to avoid confusion with `target/`
- `package directory` for what you call `root directory`, to avoid confusion with the root of the workspace
- `root directory` for the root of the workspace (you haven't named this).

**Comment by Canop** [comment]
I didn't think about the "target"... but it's not the source, it's the "intended" directory.
Do we need the workspace root directory ?

**Comment by jyn514** [comment]
I guess we don't really need the workspace.

I don't have suggestions for the general case, but here is my specific use case: the source tree for rustdoc looks like this:

```
$ tree src/librustdoc -L 1  # output abbreviated for clarity
src/librustdoc
├── Cargo.toml
├── clean
├── lib.rs
└── visit_lib.rs
```

`src` has no Cargo.toml, but the root directory has both a .toml and a .lock file. I'd prefer if I run `bacon` in `src/librustdoc` for it to watch the `librustdoc` folder but not any parent directory. Note how there is no `src` subfolder, bacon shouldn't hardcode that name.

**Comment by jyn514** [comment]
Actually, I guess this doesn't really matter since it needs to run a custom command to check only that directory ... so actually I don't have a strong preference on this and I'd rather have https://github.com/Canop/bacon/issues/9.

**Comment by Canop** [comment]
The new `Mission` struct helps make clear what is done and is logged.

When I launch bacon with

    BACON_LOG=debug cargo run -- -s ../broot/src/preview/

then the log shows

```
20:24:10 [DEBUG] (1) bacon::cli: mission: Mission {
    name: "broot",
    cargo_execution_directory: "/home/dys/dev/broot",
    cargo_command_exe: "cargo",
    cargo_command_args: [
        "check",
        "--color",
        "always",
    ],
    files_to_watch: [
        "/home/dys/dev/broot/Cargo.toml",
    ],
    directories_to_watch: [
        "/home/dys/dev/broot/src/preview",
    ],
    display_settings: DisplaySettings {
        summary: true,
    },
}
```

**Comment by Canop** [comment]
The `cargo_command_exe` and `cargo_command_args` will be changed from configuration in a near future.
