### ISSUE TITLE
UI layout optimized for bottom focus?

### ISSUE THREAD

**Issue by leeola** [Canop/bacon#19]
I've got a dashboard monitor that sits up above my monitors and Bacon's top-focused UI would be better consumed if laid out with an emphasis on the bottom of the window instead of the top.

As far as features / requirements that would be useful for this, off the top of my head:

1. The top UI of `[name] [X warnings] [X errors]` would be at the bottom of the UI.
2. The `hit q to quit, ...` UI would be at the top.
3. The listing of warnings, errors, etc would be prioritized bottom to top. So the #1 error would be on the bottom. The #2 error would be above #1. The #3 warning would be above #2, and so on.

How difficult would this feature be to include? Would the author be interested in it at all?

**Comment by Canop** [comment]
I can do it.

It means a second config file would be needed, which would be global instead of per rust project.

**Comment by Canop** [comment]
@leeola  Can you test and tell me if it looks right ?

**Comment by leeola** [comment]
One nitpick - the errors/warnings appear to be sorted correctly but weighted at the top with a larger space to the bottom. Ie, lets say my Bacon window can fit 10 errors, but i only have 3. The way it's rendering currently is the 3 errors will be at the top, with a large space between the #1 error and the bottom of the window. Here's a screenshot:

![image](https://user-images.githubusercontent.com/47556/99152910-b6750800-2659-11eb-9946-3d47983a78f0.png)

Still though, this is a huge improvement because i can see the error count at the bottom of the UI, which already helps a ton. Thank you :)

**Comment by Canop** [comment]
I see. Changing this means changing the way I scroll. I'll have a look.

**Comment by leeola** [comment]
I can live with this as is - if it matters for prioritization. Thank you :)
