### ISSUE TITLE
Feature Request: Pause?

### ISSUE THREAD

**Issue by AlJohri** [Canop/bacon#194]
When working through a large set of warnings, I would like to be able to pause `bacon` to stop re-rendering on each save. This is because on every save the list gets progressively re-rendered / re-ordered which makes it difficult to handle a set of known warnings.

The reason I would like to use bacon here instead of just just directly running `cargo check` is because it provides a nice summary view and I would like to "unpause" occasionally to start the background compilation again.

**Comment by Canop** [comment]
This makes sense.

**Comment by TheTollingBell** [comment]
There is no implementation in the rust std library to pause `Child` instances however it would be possible to just freeze accepting new output.

**Comment by Canop** [comment]
@TheTollingBell There's no technical problem here, I just lack time for writing the implementation at the moment

**Comment by Canop** [comment]
In fact, I think I just encountered a situation in which I'd like to look at a lot of warnings, and ignore most of them, by running clippy with `-W clippy::pedantic`:

![image](https://github.com/user-attachments/assets/a397f1e7-e43e-497f-b810-ee296225dbeb)

I wonder if what would be needed isn't a shortcut (with remote call API) to *acknowledge* a warning and make it go away (for a session). What's your opinion on that  @AlJohri ?
