### ISSUE TITLE
Feature Suggestion: Show number of files changed since last run in header line

### ISSUE THREAD

**Issue by DragonDev1906** [Canop/bacon#206]
I often make changes to files while bacon is still compiling (esp. before the pause functionality was added). This usually results in bacon showing slightly outdated information (which is okay), but unfortunately without any hint that it is outdated.

Ideally bacon would show a `files-changed=5` hint in the first row if the file system watcher detects that a file changed while bacon is still compiling (and thus bacon not re-starting the compilation). This should be updated immediately and should be reset to 0 when the job / a new compilation starts which includes the changed files.

I'm not sure if/when exactly cargo detects/includes these files into the compilation, but such a hint in bacon would at least indicate that the output might not include all changed files. It would also be useful when bacon is paused, to indicate how many files you've changed since bacon was paused (that is of course assuming that the filesystem watcher is still running while compiling and while bacon is paused).

**Comment by Canop** [comment]
> This usually results in bacon showing slightly outdated information (which is okay)

This isn't okay, I noticed it, it didn't happen in first versions of bacon. I'll investigate this as soon as I find some time.

**Comment by DragonDev1906** [comment]
That was a quick response :)

> This isn't okay, I noticed it, it didn't happen in first versions of bacon.

I agree, but I'm not sure what the best way to handle this case would be:

- Cancel the currently running checks by killing the process, thus delaying the results but resulting in high accuracy
    -  Should the warnings/errors found be displayed or dropped?
- Finish the currently running check (and display the results) and queue another run just after it finishes, thus giving (potentially outdated) results early, but delaying the real/final results
- (current behavior) Do not automatically add another compilation/check to the queue until any file is saved after the compilation finishes (or the user hitting F5)

Regardless of which one it is: I think it would be useful to indicate when this happens (hence the suggestion of listing the amount of files changed since the last compilation started). And perhaps whether a re-compilation is already scheduled to start when the currently running one finishes.

**Comment by Canop** [comment]
I'm trying a thing: https://github.com/Canop/bacon/pull/207

Feedback welcome

**Comment by DragonDev1906** [comment]
This works amazing, thank you.

- The change counter clearly indicates when a new compilation/check starts (by resetting to 0), (which also made testing if bacon shows outdated information easier).
- `on_change_strategy = "wait_then_restart"` works as I'd expect and I definitely prefer this over `kill_then_restart`.
- I also did not find weirdness/inconsistencies when combined with the pause feature.

A small thing I noticed (might be intentional): [default-prefs](https://github.com/Canop/bacon/blob/kill-less/defaults/default-prefs.toml) and the preference file generated using `bacon --prefs` does not contain an entry for `on_change_strategy` (thus making it harder to discover that there are two options or how to go back to the old one if desired).

### Regarding bacon showing outdated information
(feel free to copy into a different issue if it makes more sense there)
With `wait_then_restart` I **could not** get bacon to show me outdated information anymore (only during compilation which cannot be avoided since rust/cargo may read the files after it was started, but not when compilation finished).

With `kill_then_restart` I'm **still able to get bacon to print outdated information**, though I'm not sure why exactly. I think its related to how/when the output of a previous compilation run is discarded (potentially only when the process is killed).

In this screenshot I've changed a `fn test_x() {}` line in 6 files (saving all at file at once) across 4 crates that depend on each other from `test_x` to `test_y` to `test_z` (saving after each change). That first warning shouldn't be there and must have come from the second compilation (first warning it should've printed). That would also explain why it isn't the case with `wait_then_restart`, as it does not even start the second compilation (`test_y`) but directly goes to the third (`test_z`).

![2024-09-09-092622_848x551_scrot](https://github.com/user-attachments/assets/4083ac19-f991-42b8-89d6-7133b895d197)
