### ISSUE TITLE
Show failure location in summary

### ISSUE THREAD

**Issue by joshka** [Canop/bacon#208]
It would be nice to be able to keep the file location in the summary view so that it's easy to jump to the location of the failing test (I often run tests in VSCode terminal, which accepts Cmd+Click to jump to a line of code)

Normal view
```
 1  failed: tests::test1
 thread 'tests::test1' panicked at src/lib.rs:123:9:
 assertion failed: false
```

Summary view
```
 1  failed: tests::automatically
```

**Comment by Canop** [comment]
This looks like a bug that I don't reproduce right now: in my test the location line is correctly recognized and displayed in summary mode.

Can you please provide a test case ?

**Comment by joshka** [comment]
In case it wasn't clear, by file location, I meant `src/lib.rs:6:9`, not `tests:test1` as the latter does not (yet) work with vscode / rust-analyzer to navigate to tests.

**Comment by Canop** [comment]
Thanks, I reproduce. And indeed it's not a location line (as defined in the bacon model) so not really a bug, but something I hadn't thought about.

I'll have a look.

**Comment by Canop** [comment]
This should be good with https://github.com/Canop/bacon/pull/211
