### ISSUE TITLE
Allow filtering of specific tests

### ISSUE THREAD

**Issue by GeeWee** [Canop/bacon#213]
This issue is based on the [recent announcement](https://old.reddit.com/r/rust/comments/1ftc7cj/cargo_watch_is_on_life_support/) that cargo-watch is going on life support and the recommendation to switch to bacon.

I currently use both cargo-watch and bacon - but I only use cargo-watch for one case anymore really, and that is re-running a _specific_ test in a loop. Often I have a library and I just want to run one test until it's fixed, and not all the others. Currently I can't seem to find any support for this in `bacon`, apart from perhaps defining an entirely new job, which seems heavy-weight.

Would you consider adding a feature to allow passing filters to e.g. a `test` job, or does that functionality already exist and I just haven't been able to find the documentation for it?

**Comment by GeeWee** [comment]
Optimally I would love to be able to select it in bacon, but specifying it at the CLI is also perfectly fine. I just had no idea I could do it! Is it documented anywhere? If not, I can look at creating a docs PR if you'd like :)

**Comment by Canop** [comment]
> Optimally I would love to be able to select it in bacon

This could maybe be a command to just run the failing test(s). I'll create an issue for that.

> Is it documented anywhere? If not, I can look at creating a docs PR if you'd like :)

It's more or less explained here: https://dystroy.org/bacon/cookbook/#variable-arguments
The precise case of selecting the test should be made clearer, I'll improve that (if you want to create a PR, do it, but be conscious that it's very important in such doc to keep wording concise and not give too much importance to the detail you're concerned about at one moment).

**Comment by Canop** [comment]
Also thanks @GeeWee for having told me about the cargo watch author announcement.

**Comment by GeeWee** [comment]
Sounds like you have a strong opinion on how the docs update should be done, so I'll leave it to you :)
