### ISSUE TITLE
Add a command to relaunch tests but limited to the failing one(s)

### ISSUE THREAD

**Issue by Canop** [Canop/bacon#214]
(follows issue #213 and discussion with @GeeWee)

The idea would  be to hit a key and have the same test/nextest/whatever job relaunched but scoped to the failing test(s).

Hitting escape would take you back to all tests.

**Comment by GeeWee** [comment]
That would also be incredible - just like Jest's option to only rerun failing tests!

**Comment by Canop** [comment]
A serious problem is that cargo test doesn't support specifying several tests to run. Either you run them all or you run all the ones which contain a specific string.

**Comment by Canop** [comment]
Tests of the PR welcome!

**Comment by GeeWee** [comment]
I did a bit of digging, and I think a potential workaround might be to:
- List all tests
- Pass the [--skip FILTER](https://doc.rust-lang.org/rustc/tests/index.html#--skip-filter) argument to cargo test, skipping any test that passed from the list. It's a libtest argument that can be passed multitple times.
- All that's left should be the failing tests.

I'm not 100% if you'll run into issues with command length if you have a lot of tests, but it's at least a possible avenue.

**Comment by Canop** [comment]
@GeeWee Oh, I missed that. It's interesting.

**Comment by Canop** [comment]
Of course, nextest doesn't support it ^^

**Comment by GeeWee** [comment]
I think that's a good call :)
