### ISSUE TITLE
Scrolling while initial output is being collected does not have a way to keep 'following' output

### ISSUE THREAD

**Issue by jyn514** [Canop/bacon#22]
I'm not sure exactly how to describe this, and it's a bit niche so maybe it doesn't need to change.

By default, when you run `bacon` and don't type anything else, it will follow the cargo output as it runs, and earlier output will scroll off the screen. If you scroll the output while the inital output is still being collected, it will always stay at the location you scrolled to - even if you scroll back to the bottom, it won't follow the new output. It would be nice to toggle that somehow.

**Comment by Canop** [comment]
> I'm not sure exactly how to describe this

It's clear.

I think I'll just add the "is at bottom" detection as I do in other applications.
