### ISSUE TITLE
vim double-triggers bacon v2.21.0 when saving a file

### ISSUE THREAD

**Issue by narpfel** [Canop/bacon#222]
When saving a file in vim (or neovim), vim will write to multiple files in the directory of the saved file. Here is a log for saving `src/main.rs` in neovim:

```console
$ inotifywait --monitor src
Setting up watches.
Watches established.
src/ CREATE 4913
src/ OPEN 4913
src/ ATTRIB 4913
src/ CLOSE_WRITE,CLOSE 4913
src/ DELETE 4913
src/ MOVED_FROM main.rs
src/ MOVED_TO main.rs~
src/ CREATE main.rs
src/ OPEN main.rs
src/ MODIFY main.rs
src/ CLOSE_WRITE,CLOSE main.rs
src/ ATTRIB main.rs
src/ DELETE main.rs~
```

(Note that this doesn’t happen on `tmpfs` filesystems, there neovim directly writes the file. I can reproduce the shown behaviour on `btrfs` and `ext4`; I don’t have any other filesystems at hand.)

This means that with the new default for `on_change_strategy` introduced in #207, each save will run the current job (e. g. running the tests) twice. The old behaviour works well, so feel free to ignore this issue, but it might be nice to avoid retriggering anything in this situation (maybe by adding a timeout of a couple milliseconds?).

**Comment by Canop** [comment]
It looks like the problem you have is related to the write strategy of your vim installation. 

You should be able to fix this by adding this in you (n)vim config:

    set nobackup

**Comment by Canop** [comment]
All those saves happen in less than 1 ms, right ?

I wonder if this couldn't be solved with
- having the task start with a 1ms wait
- disregarding inotify events occuring during this wait

**Comment by Canop** [comment]
@narpfel Can you test with PR https://github.com/Canop/bacon/pull/233 ?
