### ISSUE TITLE
[Feature request] Ignore some messages by regex

### ISSUE THREAD

**Issue by dalance** [Canop/bacon#223]
I uses `cargo:warning` to inform some messages in `build.rs`.
This is because `cargo:info` is not supported yet.  ( https://github.com/rust-lang/cargo/issues/7037 )

bacon handles these messages as warning, but it can't be resolved.
So I think message filtering by regex may be useful.

For example, an actual message is like below:

```
warning: veryl-std@0.13.0: std hash: 158094aee3b99767fbd3cf75a1be02bf31a4aa5215dc39053c4e81a3b6617b8b
```

I expect the above message is ignored by a configuration like below

```
ignore_messages = ["warning: veryl-std@.*"]
```

**Comment by Canop** [comment]
Can you please build a minimal project demonstrating the problem ?

**Comment by dalance** [comment]
Please refer https://github.com/dalance/demo_for_bacon

**Comment by dalance** [comment]
Thank you!
