### ISSUE TITLE
[Feature] String search

### ISSUE THREAD

**Issue by crumblingstatue** [Canop/bacon#224]
Sometimes I have a huge output, and I would like to be able to quickly find a lint/error/etc. of interest.

Example use case
- I enable `clippy::pedantic`
- There is tons of warnings, so I toggle summary view to find interesting lints
- I see an interesting lint that I would like to enable, but the summary view doesn't show the lint name
- I untoggle summary view, but that resets the scroll, so I'm not at the same lint anymore
- I need a way to find that lint again in the sea of output (by searching for part of the lint message), but there is no search feature

I reflexively reach for `/`, since it's a standard binding in a pager for string search, so that would be a nice default binding for it.

**Comment by Canop** [comment]
> I reflexively reach for /, since it's a standard binding in a pager for string search, so that would be a nice default binding for it.

You can be confident I couldn't choose any other one ;)

**Comment by Jirubizu** [comment]
is there any hope for a feature like this? I would 100% use it often :D

**Comment by Canop** [comment]
Yes, there's "hope". There's just not enough free time in my days at the moment.

But upvoting this issue is helpful: it makes the issue goes up in the todo list as it make me realize that several people want it.

**Comment by Canop** [comment]
@crumblingstatue @Jirubizu Can you please test https://github.com/Canop/bacon/pull/278 ?

**Comment by Canop** [comment]
@crumblingstatue @Jirubizu Can you please check the PR #278 ?

**Comment by Canop** [comment]
done
