### ISSUE TITLE
Trying to wrap or unwrap lines in raw mode does nothing

### ISSUE THREAD

**Issue by teor2345** [Canop/bacon#234]
On macOS, when I use `toggle-raw-output` to go back to the original verbose test output, I can't wrap or unwrap lines.

Steps to reproduce:
1. Run a test with long lines and failures
2. Wait for it to finish, which goes to the fails summary screen
3. Do `toggle-raw-output` (I use my own key binding for this)
4. Try to wrap or unwrap lines

Expected outcome:
Line wrapping changes

Actual outcome:
Line wrapping does not change

If raw mode ignored wrapping entirely, that would be consistent but annoying. Instead, raw mode won't unwrap-to-wrap or wrap-to-unwrap lines.

**Comment by Canop** [comment]
Confirmed. Thanks for the report.

**Comment by Canop** [comment]
Can you check PR #235 ?
