### ISSUE TITLE
Select toolchain

### ISSUE THREAD

**Issue by anacrolix** [Canop/bacon#236]
How do I select the toolchain? I tried with `bacon +nightly`, I've tried passing it after `--`, and looked around the config files with no luck.

**Comment by Canop** [comment]
There's no direct shortcut (yet).

You can define a job with nightly:

```
[jobs.test-n]
command = ["cargo", "+nightly", "test"]
need_stdout = true
```

You can also do `rustup override set nightly` to set your project to run on nightly (then do `rustup override unset` if you don't want it anymore)

**Comment by anacrolix** [comment]
Thank you sir!
