### ISSUE TITLE
[feature request] bacon build

### ISSUE THREAD

**Issue by m4rch3n1ng** [Canop/bacon#238]
i use `cargo-watch` mostly with `cargo watch -x build` to build my project in the background, so that if i want to run it `cargo run` is instantaneous. i looked and, to me, it doesn't seem possible to do this with `bacon` currently, as `$ bacon build` gives me an `Error: job not found: "build"`

alternatives considered:
- `cargo watch` still works so i'll keep using that
- `bacon check` does not compile the project fully, so i still have to wait when i want to `cargo run`
- `bacon run` does work, but it also launches a gui application on every compile and waits until it closes to recompile, which is extremely annoying

**Comment by Canop** [comment]
bacon is meant to be configured, you can add the jobs of your choice.

For example:

```
[jobs.build]
command = [
	"cargo", "build",
	"--color", "always",
]
need_stdout = false
watch = ["benches"]
```

Please have a look at the documentation: https://dystroy.org/bacon/config/

**Comment by alerque** [comment]
You can define any jobs you want in your config:

```toml
[jobs.build]
command = ["cargo", "build"]
```

You can also as keybindings to jump to the job. There are examples linked from the home page.

**Comment by m4rch3n1ng** [comment]
ah, somehow didn't think of that. makes sense.
