### ISSUE TITLE
Consider parsing JSON output from `check` and `clippy`

### ISSUE THREAD

**Issue by CorvusPrudens** [Canop/bacon#249]
This issue is motivated by crisidev/bacon-ls#2.

bacon's [locations export](https://dystroy.org/bacon/config/#exports) doesn't surface enough information to fully describe spans in an editor. From my quick investigation, I believe this is because bacon simply parses the direct output of `check` and `clippy`, but do correct me if I'm wrong.

However, both tools can provide much more information with their JSON message formats [as described here](https://doc.rust-lang.org/cargo/commands/cargo-check.html#display-options). As far as I can tell, `json-diagnostic-rendered-ansi` provides the best of both worlds by providing detailed information along with fully rendered messages.

I don't know what the scope of such a change would be, so it's possible this is impractical. However, while it may seem a little roundabout, I've found using bacon in this way very refreshing and more reliable than rust-analyzer for my larger projects. It would be amazing if we could get accurate spans to boot!

**Comment by Canop** [comment]
> it's possible this is impractical

This would require some work but is doable. Biggest problem for me today is finding time.

**Comment by crisidev** [comment]
I am working on bacon-ls 0.4.0, but when I am done with the release, I have some time to start the MR and try to work on it.

**Comment by Canop** [comment]
@crisidev I'm working on designing a new version of the analyzer framework, in accordance with [this roadmap](https://dystroy.org/blog/bacon-everything-roadmap/). Please come [chat](https://miaou.dystroy.org/4683) about what you intend to do exactly before starting a PR.

**Comment by crisidev** [comment]
Nice, I'll join the chat to see if I can help.

After reading the roadmap, I think I can help updating the analyzers for cargo using json output, to provide precise locations.

**Comment by Canop** [comment]
Hum... The `--message-format` thing doesn't exist for `cargo test`, right ?

**Comment by crisidev** [comment]
AFAIK only in nightly.. I am not sure it has been stabilized yet..

**Comment by Canop** [comment]
@CorvusPrudens @crisidev  I've made an analyzer which reads the output of  `cargo check --message-format json-diagnostic-rendered-ansi`.

Do you think the information you'd like to see in a location export can be found ?

Analyzer reading the message: https://github.com/Canop/bacon/pull/269/files#diff-8649e54cb521dcb0d2d7aeaf0129acfa65feb8f57116e0020eb3c39ca521fee8R73-R83

Cargo message: https://docs.rs/cargo_metadata/0.19.0/cargo_metadata/enum.Message.html

If you tell me precisely what data you'd want, I can add it to the locations export.

**Comment by CorvusPrudens** [comment]
@Canop I can't speak for @crisidev as far as the implementation goes, but the main information I'd like as a user is `line_start`, `line_end`, `column_start`, and `column_end` from the [diagnostic span](https://docs.rs/cargo_metadata/0.19.0/cargo_metadata/diagnostic/struct.DiagnosticSpan.html).

I'm not sure what the ideal behavior is when there are multiple spans for one message

**Comment by Canop** [comment]
@CorvusPrudens @crisidev please have a look at https://github.com/Canop/bacon/pull/275

**Comment by CorvusPrudens** [comment]
@Canop I did some preliminary testing and it's looking great! Right out of the box it's almost exactly what I want.

The only real code change required from `bacon-ls` is that the diagnostic paths are relative (and apparently the LSP client wants absolute paths). I'm not sure if the normal locations export is doing any pre-processing to the paths to make them absolute. Anyway, this is easy enough to handle from `bacon-ls`.

I did run into a couple multi-line spans that didn't seem to show up at all, but I'm not sure where in the stack the problem with that lies. I'll be checking the exports as I go to see if it's just on the `bacon-ls` side.

Thanks so much for the changes!

**Comment by Canop** [comment]
@CorvusPrudens Yes, the standard locations export makes paths absolute: https://github.com/Canop/bacon/blob/main/src/result/report.rs#L94

This could be done in this export too, I guess, by modifying the template thing to allow eg `{span.file_name.to_absolute_path()}`.

**Comment by Canop** [comment]
@CorvusPrudens Can the PR be merged ? Do you want something fixed ?

**Comment by CorvusPrudens** [comment]
@Canop The functionality seems sufficient! I haven't been able to test everything thoroughly and some issues may pop up, but I expect they'll be no problem to address in followup issues or PRs.

**Comment by crisidev** [comment]
@Canop this is great. I haven't had much time in the last couple of weeks, but I am planning to test this out and adapt `bacon-ls` for it if needed during the xmas period.

**Comment by Canop** [comment]
@crisidev  When it's ready, you're be welcome to propose some addition to the bacon doc to explain and link to bacon-ls.

**Comment by crisidev** [comment]
@Canop I am having real trouble populating the locations file with the new analyzer.. 

This is the config I am using:

```toml
[jobs.bacon-ls]
command = [ "cargo", "clippy", "--message-format", "json-diagnostic-rendered-ansi" ]
analyzer = "cargo_json"
need_stdout = true

[exports.cargo-json-spans]
auto = true
exporter = "analyzer"
line_format = "{diagnostic.level}:{span.file_name}:{span.line_start}:{span.line_end}:{diagnostic.message}"
```

I think this should produce a file called `bacon-analyzer.json`, but nothing is generated..

**Comment by crisidev** [comment]
> @crisidev When it's ready, you'll be welcome to propose some addition to the bacon doc to explain and link to bacon-ls.

PR #289 adds documentation on how to install / use / configure bacon-ls.

**Comment by Canop** [comment]
> I think this should produce a file called bacon-analyzer.json, but nothing is generated.

By default, bacon tends to use English over American. The file is called `bacon-analyser.json`. You can change that with eg

```
[exports.cargo-json-spans]
auto = true
exporter = "analyzer"
line_format = "{diagnostic.level}:{span.file_name}:{span.line_start}:{span.line_end}:{diagnostic.message}"
path = "bacon-analyzzzer.json"

```
