### ISSUE TITLE
Also check test configuration build

### ISSUE THREAD

**Issue by mbuesch** [Canop/bacon#25]
First of all thanks for this great tool.
I use and like it a lot.

I'm currently wondering, if it's possible to run a check of the test configuration.
I do not want to actually run the tests, but just check the build. So not what `bacon test` does.
If the check of the normal build succeeds, I'd like bacon to also check the test build.

So something equivalent to this shell code:

```
cargo check && cargo check --tests
```

Is that possible (to add)?

**Comment by Canop** [comment]
We should maybe change the "check" job to

```
[jobs.check]
command = ["cargo", "check", "--tests", "--color", "always"]
need_stdout = false
```

or perhaps add a new "all" job.

**Comment by Canop** [comment]
I'm trying to determine whether there would be downsides (apart increased check latency) in changing the default job.

**Comment by mbuesch** [comment]
Thanks for the suggestion to change the jobs.check config. I'll try that.

Maybe jobs.check should default to `check --tests`, because that usually is a superset of `check`.
And then add a new optional `all` job which does `check` and subsequent `check --tests`.
And perhaps a `minimal` job which does `check` only (equivalent to the current jobs.check).

My current use case is that with the current `jobs.check` I sometimes fail to update all tests correctly. And that is only visible on an actual test run, which happens much later. Which defeats part of `bacon`s purpose to see errors while typing.

I tried `bacon test`, but that's not really a solution, because it takes way too long to execute all tests.

**Comment by Canop** [comment]
The default job in 1.0.1 includes the --tests argument.

**Comment by mbuesch** [comment]
Great, thanks!
It works fine.
