### ISSUE TITLE
`bacon run` takes 25x longer than `cargo run`

### ISSUE THREAD

**Issue by scanny** [Canop/bacon#255]
Thanks so much for this tool @Canop! Definitely a daily driver for me :)

Just wondering whether I have a setting wrong or something.

Basically, `bacon run` takes much, much longer than `cargo run`:
- The status bar turns pink right on save, so no delay there, and it stays pink right until display time.
- Stays pink for maybe 20s, varies quite a bit of course.
- `cargo run` by itself is sub-second, maybe 500ms.
- `cargo watch` time is very close to `cargo run` time.

I was wondering what `bacon` was up to during that time and maybe whether there's a setting I can change to speed things up when feedback-cycle time is more important than perhaps other things.

**Comment by Canop** [comment]
To look into a specific perf problem, I need the specific project.

I can just confirm that there's something wrong, this isn't a typical behavior.

**Comment by scanny** [comment]
Thanks @Canop :)

It looks like my comparison methodology was off here. I was comparing running `cargo run` _after_ `bacon run` had finished a cycle, so it was taking advantage of all the hard compiling work that `bacon` had done. Once I leveled that playing field the times are quite the same.

Apologies for bothering you with this :)
