### ISSUE TITLE
Vim keybindings

### ISSUE THREAD

**Issue by segeljakt** [Canop/bacon#26]
Hi, thanks for the excellent tool! Would it be possible to add vim-keybindings?

In particular:

* `j` to scroll down
* `k` to scroll up
* `G` to scroll to the bottom
* `g` to scroll to the top

**Comment by Canop** [comment]
It must be enabled in preferences.

After building from source:

    rm $(bacon --prefs) && vi $(bacon--prefs)

**Comment by segeljakt** [comment]
Cool, thank you!

**Comment by miguno** [comment]
You can do this with:

```
g = "scroll-to-top"
shift-g = "scroll-to-bottom"
```

**Comment by that-ambuj** [comment]
Before seeing this issue, I actually thought `bacon` did not support vi keybindings as it was not mentioned in the documentation. Is it OK if I submit a PR mentioning this in the docs? Just so that people wouldn't have to look for help somewhere else.

**Comment by Canop** [comment]
The right way is to change the keybindings in the prefs.

There's already a section you can just uncomment : https://github.com/Canop/bacon/blob/main/defaults/default-prefs.toml#L51-L54 but I agree it's easy to miss it.

I'm OK for a mention in the docs, probably as a TOML block to copy-paste in the config page ?

**Comment by that-ambuj** [comment]
That looks great! Thanks!

On second thought, this might sound opinionated or assumptive but I think a majority of people using bacon are familiar(and on love) with vim keybindings. When I first used bacon, I assumed it had vim keybindings by default and I was kinda disappointed.

I want to propose that we should enable vim mappings by default. Of course, we should take the community's opinion on this but my wild guess is that it's going to improve the UX for better.

**Comment by Canop** [comment]
> On second thought, this might sound opinionated or assumptive but I think a majority of people using bacon are familiar(and on love) with vim keybindings

Those users are also used to look for how to setup their familiar bindings in whatever program they use ;)

**Comment by that-ambuj** [comment]
Fair Point, I just wanted to present a UX POV on behalf of people like me :)
