### ISSUE TITLE
`--color always` revisited

### ISSUE THREAD

**Issue by joshka** [Canop/bacon#261]
Cargo has a CARGO_TERM_COLOR environment variable which can be used to force colored output.
Adding a new top level item that allows environment variables to be set for all commands seems like it might solve https://github.com/Canop/bacon/issues/124 properly without having to litter commands with `--color always` in the config.

I'd suggest expanding https://github.com/Canop/bacon/pull/146 to make global environment vars.

The workaround of setting these in the .cargo/config.toml is not quite right as that would affect all cargo usages, but I only want to affect usages of cargo from Bacon.

**Comment by Canop** [comment]
This is very interesting, I didn't know this variable.

**Comment by joshka** [comment]
> This is very interesting, I didn't know this variable.

Neither did I until yesterday :)
