### ISSUE TITLE
allow scrolling half-pages

### ISSUE THREAD

**Issue by jyn514** [Canop/bacon#264]
the `less` pager has the following keybindings:
```
  d  ^D             *  Forward  one half-window (and set half-window to N).
  u  ^U             *  Backward one half-window (and set half-window to N).
```

i use these somewhat often and miss them in bacon. bacon has two features that are kind of close:
- `scroll-line(N)`. this works but does not adapt to the window height; if i set it to a large value it skips full pages when my terminal isn't full screen; and if i set it to a small value it does not scroll a full half-page when the terminal is maximixed.
- `scroll-pages`. this only accepts integers, not fractional values

how do you feel about changing `scroll-pages` to accept a float instead of an integer? right now it gives a syntax error so it should be backwards compatible:
```
Error: Failed to parse configuration file at "/home/jyn/.config/bacon/prefs.toml"

Caused by:
    TOML parse error at line 34, column 1
       |
    34 | [keybindings]
       | ^^^^^^^^^^^^^
    Action not understood: "scroll-pages(-.5)" (did you mean "job:scroll-pages(-.5)"?)
```

**Comment by Canop** [comment]
I see no problem with that. 

If you want to try making a PR, do it. Or I'll do it.

**Comment by jyn514** [comment]
amazing! i'm not sure when i'll have time to make a PR, i'm happy for you to work on it.
