### ISSUE TITLE
Allow storing config in (project/workspace)/.config/bacon.toml

### ISSUE THREAD

**Issue by joshka** [Canop/bacon#268]
The rationale is https://dot-config.github.io/

Note this is not about XDG, but applying similar XDG-like logic to project folders to reduce the amount of cruft in the main repo tree. 

Is this something you'd consider?

**Comment by Canop** [comment]
> Is this something you'd consider?

Yes. Not just right now, though, as I'm refactoring a lot to better support non-cargo tool chains.

**Comment by alerque** [comment]
Yes, this should be an option.

Along similar lines, some projects also prefer merging tooling meta data as much as possible. My issue #241 is along those lines of allowing the config to be in the Cargo manifest. Now that Bacon also supports some other language ecosystems the same could also be done for `pyproject.toml` that can also house tooling configs.

**Comment by Canop** [comment]
When we have both `project-root/bacon.toml` and `project-root/.config/bacon.toml`, which one should override the other one ?

**Comment by Canop** [comment]
Can you check https://github.com/Canop/bacon/pull/270 ?

**Comment by joshka** [comment]
> When we have both `project-root/bacon.toml` and `project-root/.config/bacon.toml`, which one should override the other one ?
> 
> Right now it looks like the `.config` one has more chance of being a personal one (and thus should override the other one), but I'm still unsure.

I think you're right, but also one of those probably doesn't matter too much things, so either would be fine.
