### ISSUE TITLE
Doesn't stop non-terminating tests

### ISSUE THREAD

**Issue by fredrik-jansson-se** [Canop/bacon#276]
First, thanks for bacon! Absolutely mindblowing how good this tool is!

I found one issue, if you have a test that doesn't terminate because of a bug, bacon leaves that process running.

Every time I hit `t` or `n`, a new test process is launched. After quitting bacon, the processes are left running.

Please let me know if I can help!

```
fn main() {
    println!("Hello, world!");
}

#[test]
fn test() {
    loop {
        std::thread::sleep_ms(10_0000);
    }
}
```

**Comment by Canop** [comment]
Hum, I don't reproduce that.
What's your OS ?

**Comment by fredrik-jansson-se** [comment]
Mac OS. Let me check out the code and see if I can reproduce (and possibly fix).

**Comment by Canop** [comment]
Killing is done here: https://github.com/Canop/bacon/blob/main/src/exec/executor.rs#L226

Beware that this kind of thing is painful to log/trace/etc...

**Comment by fredrik-jansson-se** [comment]
Cool, I'll give it a shot!

Thanks for the pointer!

**Comment by fredrik-jansson-se** [comment]
I can reproduce this on Linux as well.
```
$ bacon
(hit `t` to launch test, then `q` to quit)
$ ps aux | grep zomb
frja     2152961  0.0  0.0  72260  2880 pts/6    Sl   21:11   0:00 /home/frja/bacon-zombie/target/debug/deps/bacon_zombie-ab96b146d87eb3ef --exact test --nocapture
```

Not entirely sure, but the `MissionExecutor::kill_command` is None for me. It seems to come from `Job::kill`, and I don't see anywhere where a job's kill is set.

Am I misunderstanding something?

**Comment by Canop** [comment]
`kill_command` is usually `None`. It can be specified with the `kill` argument of the job: https://dystroy.org/bacon/config/#job-properties

**Comment by fredrik-jansson-se** [comment]
Yeah, sorry, now I see... it's the process handle's kill fn that's called. 

Weird that you can't reproduce.... 

I'll keep at it

**Comment by fredrik-jansson-se** [comment]
Ok! Seems something has changed in cargo (if this worked before).

I can reproduce this w/o bacon:
```
cargo test
running 1 test
# This is now hanging in the test
pkill -9 cargo
[1]    93425 killed     cargo test
```
BUT
```
 ps aux | grep zom
frja             93426   0.0  0.0 410595968   1872 s018  S     9:31PM   0:00.00 /Users/frja/dev/rust/tmp/bacon-zombie/target/debug/deps/bacon_zombie-c7026433aab84bb9
```

So this is clearly to bacon related. 

I'll close this issue.

**Comment by Canop** [comment]
Hum. You mean it hanged for you because you had an older version of rust ?

**Comment by fredrik-jansson-se** [comment]
https://github.com/rust-lang/cargo/issues/14929

**Comment by fredrik-jansson-se** [comment]
I.e. like this:
```
$ cargo test &
[1] 2155724
     Running unittests src/main.rs (target/debug/deps/bacon_zombie-ab96b146d87eb3ef)

running 1 test

$ ps
    PID TTY          TIME CMD
2152410 pts/6    00:00:00 zsh
2155724 pts/6    00:00:00 cargo
2155742 pts/6    00:00:00 bacon_zombie-ab
2155760 pts/6    00:00:00 ps

$ pkill -9 cargo
[1]  + 2155724 killed     cargo test

$ ps
    PID TTY          TIME CMD
2152410 pts/6    00:00:00 zsh
2155742 pts/6    00:00:00 bacon_zombie-ab
2155799 pts/6    00:00:00 ps
```
