### ISSUE TITLE
Typo on "Are they bacon yet" website

### ISSUE THREAD

**Issue by c-git** [Canop/bacon#283]
# TLDR

[On the Are they bacon yet?](https://dystroy.org/blog/are-they-bacon-yet/) website under ruff it says "Exemple configuration:" and I suspect that is supposed to be "Example configuration"

I'm amazed at how good this tool is. After running into the old bug and upgrading as a result almost all the features I wanted in the old version are implemented now and more than that it has features I didn't know I wanted.

**Comment by Canop** [comment]
Thanks for telling me about the typo (*example* is a difficult word for me as it's*exemple* in French, coming from Latin *exemplum*).

And thanks for the kind words.

**Comment by c-git** [comment]
It's fixed now.
