### ISSUE TITLE
Hot reloading not working for me

### ISSUE THREAD

**Issue by niteshbalusu11** [Canop/bacon#288]
This is my `bacon.toml` and I am running `bacon dev`. It doesn't seem to be hot reloading on save unless I manually press F5. Am I missing something? I apologize for opening an issue. I just couldn't seem to find a solution.

```
[jobs.dev]
command = ["cargo", "run", "--", "--config-path", "/home/nitesh/Documents/zbd/lightning-interceptor-service/rust/config.toml"]
need_stdout = true
env = { "RUST_LOG" = "debug" }
```

**Comment by Canop** [comment]
> Am I missing something? 

Nothing obvious, I think.

Can you tell more on your OS and version of bacon ? Can you confirm it happens whatever the editor you use for saving files ? And that the files you saved aren't git-ignored ?
Can you provide the log you get when launching bacon in debug log mode (eg `BACON_LOG=debug bacon dev`)

**Comment by niteshbalusu11** [comment]
No they aren't gitignored. My dir structure is like this.

lightning-interceptor-service -> this is where .git directory is
lightning-interceptor-service/rust -> this is where bacon is running.

I am not sure if it matters. Attaching the logs.
[bacon.log](https://github.com/user-attachments/files/18276390/bacon.log)

**Comment by niteshbalusu11** [comment]
Also, I am on Ubuntu, bacon version 3.3.0

**Comment by Canop** [comment]
Is your program long running ?

If so you'll probably have to adapt the job, see https://dystroy.org/bacon/cookbook/#long-running-programs

For example:

```
[jobs.dev]
command = ["cargo", "run", "--", "--config-path", "/home/nitesh/Documents/zbd/lightning-interceptor-service/rust/config.toml"]
need_stdout = true
env = { "RUST_LOG" = "debug" }
background = false
on_change_strategy = "kill_then_restart"
kill = ["kill", "-s", "INT"]
```
