### ISSUE TITLE
Automatically re-configure/re-run on updates to bacon.toml

### ISSUE THREAD

**Issue by cpick** [Canop/bacon#29]
I've been testing various custom jobs by adding them to and editing "bacon.toml".

Currently my flow is:
1. Edit "bacon.toml".
2. Kill current `bacon`.
2. Re-run `bacon <custom_job>`.

I think it would be nice if `bacon` watched "bacon.toml" for updates and restarted itself to load the new configuration and try any changes.

If this sounds like a useful feature I wouldn't mind taking a try at implementing it.

Thanks for a great tool!

**Comment by Canop** [comment]
I didn't think this would be needed but I have no objection.

If you don't find an obvious clean way to code it, I'll do it myself.

**Comment by Canop** [comment]
Now, do we also want to track the preferences files ?
