### ISSUE TITLE
Add support on command-line for cargo features

### ISSUE THREAD

**Issue by bruceg** [Canop/bacon#31]
I am working on a project (https://github.com/timberio/vector) that uses a large number of features in cargo. I frequently want to run the compilation with ad-hoc features turned on, typically using `--no-default-features` to reduce the rebuild cycle time. It is infeasible to create a `bacon.toml` file that contains a job specification for each one of the features, particularly when combined with permutations of flags like `--lib`, `--tests`, or using `clippy`. As such, I am reduced to editing `bacon.toml` each time I need different feature flags enabled. Support for adding these options dynamically using command line flags would be very helpful.

**Comment by Canop** [comment]
This looks feasible.

(as I was curious, the correct link to your project is https://github.com/timberio/vector)

**Comment by jyn514** [comment]
This would need https://github.com/google/argh/issues/78 or something like it I think.

**Comment by Canop** [comment]
In a first version, I could support --no-default-features and --features directly at the bacon level by rewriting the command

**Comment by jyn514** [comment]
Then you have to support those arguments even after adding support for arbitrary options, though. And I do think the arbitrary options are good to have eventually, that would get rid of most of the need for `bacon.toml`.

**Comment by Canop** [comment]
Can you please confirm it's OK before I issue a new release ?

**Comment by bruceg** [comment]
This works for me, thanks.
