### ISSUE TITLE
Workspace Support

### ISSUE THREAD

**Issue by nikhilmitrax** [Canop/bacon#4]
Hello,

Thanks for the tool! I noticed it does not directly support compiling workspaces. That's a situation where, imho, this tool would be quite valuable. I don't know about the effort involved, but it would be useful to support workspaces.

**Comment by Canop** [comment]
I've never used workspaces but it's probably not a big change.

I'll have a look (not right now).

**Comment by jyn514** [comment]
This works fine for me with workspaces.

**Comment by jyn514** [comment]
Ok, I found the issue - `bacon` assumes there is a `src/` directory. Instead, it could look for all targets and find their source directories, something like this:

```
cargo metadata | jq '.packages[] |select(.source == null) | .targets[].src_path'
```

**Comment by jyn514** [comment]
As a bonus, that will work regardless of what directory you're in, since it uses the top-level metadata and outputs absolute paths.

**Comment by nikhilmitrax** [comment]
@jyn514 That approach would lead to double-watching workspace members that define multiple entrypoints (such as multiple binaries). I'm not sure if that's an issue we need to deal with, but it seems the canonical way to understand workspace members is to parse it off of `Cargo.toml`.

Of course, you could do a bit of hackery and iterate over the `src_path`, checking if `src_path.parent()` contains `Cargo.toml` to find the exact workspace members.


This actually brings up another interesting issue where all `benches`, `examples` and `tests` are excluded from bacon since those files won't be watched.

**Comment by nikhilmitrax** [comment]
I wrote up a small MVP of the idea.

https://github.com/Canop/bacon/pull/14

**Comment by mikart143** [comment]
I have an issue but I do not now if it is related to workspaces. I have a workspace and I try to run bacon in workspace project but it keeps saying that it passed. I do not run in workspace root but in the sub project.

**Comment by Canop** [comment]
@mikart143  The current version is quite rough: it executes `cargo watch` in the directory you launch it into.

**Comment by mikart143** [comment]
So teoritically it should work beause it executes in my project not in workspace root. Is there any way to get any logs ? I treid to run it inside src folder but i said that it should be executed in project root

**Comment by Canop** [comment]
You can get and follow a bacon.log file by launching bacon with `BACON_LOG=debug bacon`

Side note: you can go to my chat if necessary: https://miaou.dystroy.org/3

**Comment by Canop** [comment]
bacon should now work for workspaces. Can you confirm ? Infirm ?

**Comment by nikhilmitrax** [comment]
Ran into a compile issue while trying to `cargo install --force bacon`

```
error[E0658]: non-builtin inner attributes are unstable
 --> /Users/<username>/.cargo/registry/src/github.com-1ecc6299db9ec823/semver-parser-0.10.1/src/generated.rs:4:1
  |
4 | #![rustfmt::skip]
  | ^^^^^^^^^^^^^^^^^
  |
  = note: for more information, see https://github.com/rust-lang/rust/issues/54726
  = help: add `#![feature(custom_inner_attributes)]` to the crate attributes to enable```

**Comment by jyn514** [comment]
@nikhilmitrax that looks like an old version of rustc, try updating.

**Comment by nikhilmitrax** [comment]
Updated to latest nightly.

I can confirm it works in workspaces. Closing the issue. Thank you very much for the change!

P.S. It might be useful to define some MSRV for bacon.
