### ISSUE TITLE
Missing --help test for check-all

### ISSUE THREAD

**Issue by emilk** [Canop/bacon#41]
Thanks for a great project!

`bacon check-all` is arguably the most common command for bacon, yet it is not mentioned in the help text of `bacon --help`.

**Comment by emilk** [comment]
nevermind, I'm stupid. `check-all` is the name of a job, not a command to bacon.

**Comment by Canop** [comment]
If you have an idea regarding how to make it clearer, it could be useful for other to avoid the same confusion.

**Comment by emilk** [comment]
What I was looking for was really a command to run all the jobs: https://github.com/Canop/bacon/issues/42
