### ISSUE TITLE
tests folder is not watched by test job

### ISSUE THREAD

**Issue by CGMossa** [Canop/bacon#44]
I'm unsure if this is a bug or design: The integration-test folder `/tests/` is ignored (not watched) by bacon.

I think I've fixed it by adding `watch = ["tests"]` to a toml file, but I think this folder should be watched by default.

**Comment by Canop** [comment]
Do you happen to have either an old version of bacon or an old bacon.toml file ?

The current default job configuration is 

```
[jobs.check]
command = ["cargo", "check", "--color", "always"]
need_stdout = false

[jobs.check-all]
command = ["cargo", "check", "--all-targets", "--color", "always"]
need_stdout = false
watch = ["tests", "benches", "examples"]

[jobs.clippy]
command = ["cargo", "clippy", "--color", "always"]
need_stdout = false

[jobs.test]
command = ["cargo", "test", "--color", "always"]
need_stdout = true
watch = ["tests"]
```

Note that if you have an old bacon.toml file, using a new version of bacon doesn't remove it. You must either fix it yourself or recreate it.

**Comment by CGMossa** [comment]
Just to give a quickl reply: `bacon 1.1.3`.

**Comment by Canop** [comment]
Upgrade to 1.1.4. The "tests" directory wasn't watched in version 1.1.3

See CHANGELOG: https://github.com/Canop/bacon/blob/main/CHANGELOG.md#v114---20210210

**Comment by CGMossa** [comment]
So sorry for this redundant issue. Will close this now.
Thank you for your contribution and reply.
