### ISSUE TITLE
Failing doctest doesn't display nicely with `bacon -j test`

### ISSUE THREAD

**Issue by LovecraftianHorror** [Canop/bacon#49]
Having a failing doctest causes bacon to just display the raw test output instead of formatting it nicely for the user

## Reproduction

Having a lib with the doctest

```rust
//! ```
//! panic!()
//! ```
```

and then running `bacon -j test` results in

![image](https://user-images.githubusercontent.com/30302768/124401010-a7c88780-dcf4-11eb-93a8-44899781f14e.png)

**Comment by Canop** [comment]
If you confirm it looks OK to you too, I'll probably release a new version soon.

(if you have other concerns or doubts, don't hesitate to come to [the chat](https://miaou.dystroy.org/3768))

**Comment by LovecraftianHorror** [comment]
Thanks for the fast responses! I would have tried making the changes myself, but I've been busy and am not familiar with the codebase so I figured the least I could do was file issues

The only problem that I noticed is that there isn't much information included in the output from a failed doctest (likely because the output format is different than unit and integration tests)

As an example this doc-comment with a `panic`ing example

```rust
//! ```
//! println!("stdout context");
//! eprintln!("stderr context");
//! panic!();
//! ```
```

results in this with `bacon -j test` on the current `main`

![image](https://user-images.githubusercontent.com/30302768/124629129-25080f80-de4f-11eb-9e61-6328885d2769.png)

While the output of `cargo test` is this

```text
    Finished test [unoptimized + debuginfo] target(s) in 0.00s
     Running unittests (target/debug/deps/repro-a6abdff713820393)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

   Doc-tests repro

running 1 test
test src/lib.rs - (line 1) ... FAILED

failures:

---- src/lib.rs - (line 1) stdout ----
Test executable failed (exit code 101).

stdout:
stdout context

stderr:
stderr context
thread 'main' panicked at 'explicit panic', src/lib.rs:5:1
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace



failures:
    src/lib.rs - (line 1)

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.18s

error: test failed, to rerun pass '--doc'
```

This output format differs from unit and integration tests since the stdout and stderr output is split up into different sections under `stdout` compared to unit/integration tests that include everything in one segment like so

```
failures:

---- unit_test stdout ----
stdout context
stderr context
thread 'unit_test' panicked at 'explicit panic', src/lib.rs:11:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    unit_test
```

If you want any other information or input then just let me know.

**Comment by Canop** [comment]
I'll probably release a new version as there's already an improvement but you're right it would be better to try capturing the stdout and stderr of the test.

**Comment by Canop** [comment]
I had to made myself familiar again with this codebase too... I wrote this such a long time ago..
But I understand it again and I can do the adaptations. It's mostly trying to find what can be reasonably considered as a marker of some kind of content.

I seem to have found something correct, breaking nothing, and capturing the relevant parts of stdout and stderr in test failures too:

![image](https://user-images.githubusercontent.com/617006/124658558-2f082d80-dea4-11eb-838d-dfce646e6004.png)
![image](https://user-images.githubusercontent.com/617006/124658687-59f28180-dea4-11eb-9876-783c1c17cd59.png)

**Comment by LovecraftianHorror** [comment]
That looks great! If you push your changes I'll be sure to give everything a thorough test to make sure things all work right

And thanks for taking the time to look into all this! `bacon` has become a vital part of my rust dev workflow so I appreciate all the time and effort it took to get it to this point

**Comment by Canop** [comment]
I just pushed, after many tests.

Feel free to reopen if you see problems.
