### ISSUE TITLE
Tabs seem to be stripped from output in `bacon -j test`

### ISSUE THREAD

**Issue by LovecraftianHorror** [Canop/bacon#50]
## Reproduction

A crate with

```rust
#[test]
fn demo() {
    println!("    Space    Separated");
    println!("\tTab\tSeparated");
    panic!();
}
```

and then running `bacon -j test` results in

![image](https://user-images.githubusercontent.com/30302768/124401079-5ff63000-dcf5-11eb-97e0-e20d0bd57687.png)

So tabs aren't present from the second `println!()` even though the tabs are present in the output of `cargo test`

**Comment by Canop** [comment]
Thanks for the reproduction snippet. I'll have a look
