### ISSUE TITLE
Add a way to scroll errors

### ISSUE THREAD

**Issue by jyn514** [Canop/bacon#6]
There doesn't appear to be a way to show more errors than the top 4 without changing to summary mode.

![errors](https://user-images.githubusercontent.com/23638587/98088467-79d23100-1e4f-11eb-9113-cb12cd1973af.png)

**Comment by Canop** [comment]
Yes. Will do. With arrow keys and mouse wheel.

**Comment by jyn514** [comment]
Page-up/page-down would also be nice :)

**Comment by jyn514** [comment]
> Side note: I didn't need it for now because bacon encourages you to just fix error after error until there's none.

I'll have to try out bacon more, but the reason I expect to use this is my codebases with the most errors are also the largest, so compile times are really bad, so it's feasible for me to fix all the errors on the screen before getting _any_ updated feedback at all.

**Comment by Canop** [comment]
@jyn514 I closed but I'd like your confirmation the current behaviour is OK.

**Comment by jyn514** [comment]
@Canop it works very well, except that if you scroll to the bottom and then enter summary mode, it will show you a blank screen until you scroll for the first time.

**Comment by jyn514** [comment]
Also, it would be nice for spacebar to scroll down too, but I can live with only page-up/down.

**Comment by Canop** [comment]
oh... I didn't think about the summary mode. I'll try to ensure the same item is on top when toggling.

**Comment by Canop** [comment]
@jyn514 If it doesn't feel OK to you, please reopen (you're allowed to do it on all issues, anyway)
