### ISSUE TITLE
Will not install on Ubuntu 21.10 with 25 Errors

### ISSUE THREAD

**Issue by JonathanLindsey** [Canop/bacon#63]
I am on Ubuntu Linux 12.10. When I run `cargo install bacon` I get [several errors](https://pastebin.com/qBgwG0Xc).

**Comment by Canop** [comment]
Can you please give me the output of `cargo --version` and `rustc --version` ?

**Comment by JonathanLindsey** [comment]
I ran `rustup update` and then `cargo install bacon` again. Appears to be the same 25 errors.

Then ran those version commands:

cargo 1.56.0 (4ed5d137b 2021-10-04)

rustc 1.56.1 (59eed8a2a 2021-11-01)

**Comment by Canop** [comment]
Ok, found it.

There's apparently a breaking change between anyhow 1.0.44 and anyhow 1.0.49...

**Comment by Canop** [comment]
TBH I did import `anyhow::*` in a few place, thinking there wouldn't be any new type in anyhow. It's also my fault, not sure I can say it's a *breaking change*.

**Comment by JonathanLindsey** [comment]
It's working now. Thank you!
