### ISSUE TITLE
Bacon 2

### ISSUE THREAD

**Issue by Canop** [Canop/bacon#66]
Bacon 2 is developed in the "bacon2" branch.

It makes possible to

* run jobs like `cargo run` (and see the output)
* run jobs like `cargo doc --open` (but not have it opening again and again)
* bind a job to a key combination of your choice
* change the key combinations for all internal functions (wrapping, quitting, etc.)

It comes with a help page listing all the configured key combinations, and I'll set up a site because while the simple use didn't change, some more complex uses are less obvious.

This will solve #47 and #52

Apart the web site, bacon 2 is mostly done. Now would be a good time to test it, comment.

**Comment by jyn514** [comment]
I still think something like https://github.com/google/argh/issues/78 would be useful. The handling for `doc-open` is clever and I like that I can call it from the main job with a shortcut :)

**Comment by Canop** [comment]
@jyn514 Replacing argh isn't out of question. I'm pondering whether passing arguments this way is worth the task or not. Would that be used a lot ?

**Comment by Canop** [comment]
Site almost ready: https://dystroy.org/bacon/

**Comment by jyn514** [comment]
@Canop I don't think there's any need to write your own parsing library, you could use gumdrop or clap or something which both support `--` as a delimiter.

**Comment by Canop** [comment]
Is there an issue declared here for passing arguments after `--` ? I don't find one.

**Comment by Canop** [comment]
Hum, I was more imagining adding the arguments to a base job, for example

    bacon ex -- bla -v some-arg

(assuming a "ex" job)

or

    bacon -- -p my_crate_in_workspace

to take your example but assuming a base `check` job.

**Comment by Stargateur** [comment]
TODO: check if clap brand new 3 handle it. I believe 2 already handle this.

**Comment by cehteh** [comment]
on bacon 1.2 I have sometimes the issue that a borked test runs very long. Does bacon 2 offer some way (ctrl-c?) to kill the current subprocess (ideally some hook for nice level / ulimits would be nice too). If not I can make separate tickets for these.

**Comment by Canop** [comment]
@cehteh Doesn't ctrl-c work well in bacon ? It was designed for that.
(note that I still have to do the same for the case of reverting to a previous process)
