### ISSUE TITLE
Add support for `--cap-lints warn`

### ISSUE THREAD

**Issue by jyn514** [Canop/bacon#7]
Often when I'm doing major refactorings I end up with lots of warnings about unused imports, etc. It would be nice to be able to disable these.

Here's the script I used before `bacon`, for reference:

```
$ cat $(which check-color)
#!/bin/sh
# This script is meant for when you have so many errors the first ones go off the screen.
cargo rustc --lib --profile check --color always -- --cap-lints warn -A warnings "$@" 2>&1 | less -R
```

Note how it uses `--cap-lints warn` to avoid codebases adding `forbid(warnings)` at the top of the file.

**Comment by Canop** [comment]
But why ? Warnings are shown after errors in bacon, so that they don't get in the way: you fix errors then warnings.

**Comment by jyn514** [comment]
Oh I see, that's a nice feature. Bacon doesn't have --cap-lints, though:

```
 docs.rs   1 error  

 1  error: unused import: `std::process::Command`
  --> src/lib.rs:6:5
```

**Comment by Canop** [comment]
Looks like a good idea.

Related: https://github.com/Canop/bacon/issues/9
