### ISSUE TITLE
Line wrapping when using run

### ISSUE THREAD

**Issue by auronandace** [Canop/bacon#71]
I noticed there is a w keybinding in the help section that toggles wrapping. What exactly is getting wrapped?

When I press r to run cargo build and my program produces output none of the lines wrap. Pressing w seems to have no effect there. Am I missing something?

I'm running alacritty 0.10.0 and bacon 2.0.1

**Comment by Canop** [comment]
Here's what you're supposed to see (assuming there are errors or warnings and the terminal is tiny).

Unwrapped (end of lines missing):

![image](https://user-images.githubusercontent.com/617006/154813761-06170e64-7d0b-4c3e-89a7-bca03f82d1a0.png)

Wrapped (end of lines wrapped):

![image](https://user-images.githubusercontent.com/617006/154813778-6adefd81-9ea6-4aa8-bcd1-100b7260e85d.png)

**Comment by auronandace** [comment]
Are there any plans to make wrapping work when you're in run mode?

**Comment by Canop** [comment]
There's this issue now. Added to the todo list.
