### ISSUE TITLE
Detect and use cargo aliases as jobs

### ISSUE THREAD

**Issue by poliorcetics** [Canop/bacon#77]
I have an alias in `.cargo/config` that is `clw = "clippy --target x86_64-pc-windows-msvc --all-targets"`.

`bacon -j clw` finds nothing and I don't want to duplicate all my aliases into a bacon config file each time I add aliases for a project

Maybe with a new flag `-a / --alias` to make it clear it's not using a normal bacon job ?

**Comment by Canop** [comment]
Do you know of a way to load those aliases in Rust (I mean without looking for the config file and parse it) ?

**Comment by poliorcetics** [comment]
I don't, except for parsing the file. And it's not even the end since they can be defined in `$CARGO_HOME/config(.toml)` and `$HOME/.cargo/config(.toml)`.

One way I can see to do it safely (I think, untested and I haven't looked at the internals of `bacon` yet):

- Accept a `--alias` flag (placeholder name) that takes one argument, the alias' name
- Accept the normal job arguments after `--` when user wants them (calls would be like `bacon --alias clw` or `bacon --alias clw -- --all-features`)
- Try running `cargo <alias> --message-format=json` (or maybe ask users to pass `--message-format=json` / its equivalent ?)
- Parse result as usual

**Comment by Canop** [comment]
This looks reasonable. I could have a `--alias` argument and just trust that there's really an alias with that name.
In that case I would probably need a way to properly declare the arguments added to all jobs and aliases by by default (i.e. usually `"--color", "always"`)

(bacon doesn't use `--message-format=json` because it didn't exist)

**Comment by Canop** [comment]
Can you please confirm it's OK for you with the last commit ?

You can now launch a cargo alias with `bacon alias:my_alias`
