### ISSUE TITLE
Add option to forcefully cancel job on changes

### ISSUE THREAD

**Issue by nolanderc** [Canop/bacon#78]
Currently, if the running job gets stuck in an infinite loop bacon  becomes unresponsive. This is easily reproduced by running `bacon test` in a project containing the following:

```rust
#[test]
fn infinite() {
    loop {}
}
```

Pressing Ctrl+C does not work, and neither does making changes to any source files (tested on macOS 12.0.1).

This is also relevant when running a server in a compile-edit-run cycle using `bacon run`, as these programs aren't expected to automatically terminate, but frequent rebuilds are useful.

This problem is solved in [`watchexec`](https://github.com/watchexec/watchexec) by using a flag (`--restart`) which forcefully terminates the running command if there are any changes to watched files.

Something similar could be added to bacon, either as an option in the configuration file, or as a command line flag.

**Comment by nolanderc** [comment]
After some digging I have traced the problem to this line in the executor: https://github.com/Canop/bacon/blob/d256ebcb7e2244bcad335abccafb8ab84fc8aea2/src/executor.rs#L135

Basically, the executor is blocked on reading the next line from `cargo test`, but since the test is stuck, there is no output to be read and the executor is stuck. This leaves it unable to receive events from other threads. Working on a fix...

**Comment by Canop** [comment]
I don't know why this issue wasn't closed...
