### ISSUE TITLE
bacon --prefs only works in rust project.

### ISSUE THREAD

**Issue by SebastianJL** [Canop/bacon#84]
I usually use `nvim $(bacon --prefs)` to configure bacon. I just found out that `bacon` needs to be run in a rust project. This makes sense I guess for most other commands but it would be nice if given the `--prefs` option this would work from anywhere on the system. 
The exact error is as follows:
```bash
$ bacon --prefs
Error: Cargo.toml file not found.
bacon must be launched 
* in a rust project directory
* or with a rust project directory given in argument
(a rust project directory contains a Cargo.toml file or has such parent)
```

If anyone can give me some pointers or the `OK` that this is a change that is desired I'll try and implement it myself.

**Comment by Canop** [comment]
You seem to be totally right.

I can do the change, unless you prefer to do it yourself.

**Comment by SebastianJL** [comment]
@Canop Thanks a lot😊

**Comment by Canop** [comment]
@SebastianJL  If you look at the commit you'll see this wasn't really a lot of work :)

**Comment by SebastianJL** [comment]
Yeah of course but it's nice you reacted to my issue and fixed it.
