### ISSUE TITLE
Use bacon with a build.rs script that modifies source files

### ISSUE THREAD

**Issue by jsimonrichard** [Canop/bacon#85]
I would like to be able to use bacon with the project I'm currently working on, but the project has a `build.rs` script that generates source files (from protobuf definitions, if you're curious). When clippy (or check) runs, it runs the `build.rs` script again to make sure everything is up-to-date. However, this changes the source files, so bacon runs clippy again. It gets stuck in a loop.

**Proposed Chage:**
Add a command line option or a config option for excluding a directory from being watched.

**Comment by Stargateur** [comment]
build.rs should re run if nothing change, have you put some strange like in your build.rs to ask cargo to rerun everytime ?

**Comment by jsimonrichard** [comment]
My `build.rs` script creates other `.rs` files inside `./src`. It's not asking cargo to run directly, but since it's updating the files inside `./src` I assumed that that's what is prompting bacon to rerun clippy.

On a side note, I can confirm that running clippy on its own works just fine. This behavior only occurs when running clippy with bacon.

**Comment by Stargateur** [comment]
it would help to have a reproduction example.

**Comment by jsimonrichard** [comment]
Here's one: https://github.com/jsimonrichard/bacon-buildrs-reprex/tree/master

I did also try this with https://github.com/watchexec/cargo-watch using the command
```
cargo watch -x clippy -i ./src/mymod.rs
```
The `-i` flag is supposed to ignore `mymod.rs`, but it gets stuck in a loop as well.

**Comment by Stargateur** [comment]
It's more up to how cargo see thing, I recommend to not put generated file in src folder, that not a good practice, you can see the [example](https://doc.rust-lang.org/cargo/reference/build-script-examples.html) of build.rs:

```rust
// build.rs

use std::env;
use std::fs;
use std::path::Path;

fn main() {
    let out_dir = env::var_os("OUT_DIR").unwrap();
    let dest_path = Path::new(&out_dir).join("mymod.rs");
    fs::write(
        &dest_path,
        "pub fn message() -> &'static str {
            \"Hello, World!\"
        }
        "
    ).unwrap();
    println!("cargo:rerun-if-changed=build.rs");
}
```

`OUT_DIR` is where you should put your artefact then in your code you can do:

```rust
include!(concat!(env!("OUT_DIR"), "/mymod.rs"));
```

This is both more portable and would avoid your problem if you really wish to keep your generated file in src you could add this to your Cargo.toml:

```toml
exclude = ["src/mymod.rs"]
```

**Comment by jsimonrichard** [comment]
Makes sense, thanks
