### ISSUE TITLE
v1.2.5 and up fails to install on windows

### ISSUE THREAD

**Issue by Fluhzar** [Canop/bacon#87]
All errors come from attempting to install `bacon` through `cmd` with the toolchain `stable-x86_64-pc-windows-msvc` via `cargo install bacon@{version}` where `{version}` is any of the version from `1.2.5` through `2.2.2`.

For the most recent versions, v2.2.1 and v2.2.2, the only error is this:

```
error[E0599]: no method named `enable_io` found for struct `tokio::runtime::Builder` in the current scope
  --> C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.2\src\executor.rs:57:18
   |
57 |                 .enable_io()
   |                  ^^^^^^^^^
   |                  |
   |                  private field, not a method
   |                  help: there is an associated function with a similar name: `enable_all`

For more information about this error, try `rustc --explain E0599`.
error: could not compile `bacon` due to previous error
```

Since the changes for v2.2.1 resolved all but the one above error I don't think it's particularly useful to share these errors, but if desired the errors I encounter when attempting to install any version of `bacon` from v1.2.5 through v2.2.0 are along the lines of:

<details>
<summary>v2.2.0 errors</summary>

<pre>
error[E0308]: mismatched types
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\app.rs:47:21
   |
46 |                 match user_event?.event {
   |                       ----------------- this expression has type `crokey::crossterm::event::Event`
47 |                     Event::Resize(mut width, mut height) =&gt; {
   |                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected enum `crokey::crossterm::event::Event`, found enum `crossterm::event::Event`
   |
   = note: perhaps two different versions of crate `crossterm` are being used?

error[E0308]: mismatched types
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\app.rs:57:21
   |
46 |                 match user_event?.event {
   |                       ----------------- this expression has type `crokey::crossterm::event::Event`
...
57 |                     Event::Key(key_event) =&gt; {
   |                     ^^^^^^^^^^^^^^^^^^^^^ expected enum `crokey::crossterm::event::Event`, found enum `crossterm::event::Event`
   |
   = note: perhaps two different versions of crate `crossterm` are being used?

error[E0277]: the trait bound `crokey::CroKey: std::convert::From&lt;crossterm::event::KeyEvent&gt;` is not satisfied
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\app.rs:58:51
   |
58 |                         debug!(&quot;key pressed: {}&quot;, CroKey::from(key_event));
   |                                                   ^^^^^^^^^^^^ the trait `std::convert::From&lt;crossterm::event::KeyEvent&gt;` is not implemented for `crokey::CroKey`
   |
   = help: the trait `std::convert::From&lt;crokey::crossterm::event::KeyEvent&gt;` is implemented for `crokey::CroKey`

error[E0277]: the trait bound `crokey::CroKey: std::convert::From&lt;crossterm::event::KeyEvent&gt;` is not satisfied
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\app.rs:59:50
   |
59 |                         action = keybindings.get(key_event);
   |                                              --- ^^^^^^^^^ the trait `std::convert::From&lt;crossterm::event::KeyEvent&gt;` is not implemented for `crokey::CroKey`
   |                                              |
   |                                              required by a bound introduced by this call
   |
   = help: the trait `std::convert::From&lt;crokey::crossterm::event::KeyEvent&gt;` is implemented for `crokey::CroKey`
   = note: required because of the requirements on the impl of `Into&lt;crokey::CroKey&gt;` for `crossterm::event::KeyEvent`
note: required by a bound in `keybindings::KeyBindings::get`
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\keybindings.rs:58:20
   |
58 |     pub fn get&lt;CK: Into&lt;CroKey&gt;&gt;(&amp;self, key: CK) -&gt; Option&lt;&amp;Action&gt; {
   |                    ^^^^^^^^^^^^ required by this bound in `keybindings::KeyBindings::get`

error[E0599]: no method named `enable_io` found for struct `tokio::runtime::Builder` in the current scope
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\executor.rs:57:18
   |
57 |                 .enable_io()
   |                  ^^^^^^^^^
   |                  |
   |                  private field, not a method
   |                  help: there is an associated function with a similar name: `enable_all`

error[E0308]: mismatched types
   --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\help_page.rs:45:47
    |
45  |         skin.italic = CompoundStyle::new(Some(AnsiValue(204)), None, Attribute::Bold.into());
    |                                          ---- ^^^^^^^^^^^^^^ expected enum `crokey::crossterm::style::Color`, found enum `crossterm::style::Color`
    |                                          |
    |                                          arguments to this enum variant are incorrect
    |
    = note: perhaps two different versions of crate `crossterm` are being used?
note: tuple variant defined here
   --&gt; C:\Users\------\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\option.rs:526:5
    |
526 |     Some(#[stable(feature = &quot;rust1&quot;, since = &quot;1.0.0&quot;)] T),
    |     ^^^^

error[E0277]: the trait bound `crokey::crossterm::style::Attributes: std::convert::From&lt;crossterm::style::Attribute&gt;` is not satisfied
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\help_page.rs:45:86
   |
45 |         skin.italic = CompoundStyle::new(Some(AnsiValue(204)), None, Attribute::Bold.into());
   |                                                                                      ^^^^ the trait `std::convert::From&lt;crossterm::style::Attribute&gt;` is not implemented for `crokey::crossterm::style::Attributes`
   |
   = help: the following other types implement trait `std::convert::From&lt;T&gt;`:
             &lt;crokey::crossterm::style::Attributes as std::convert::From&lt;&amp;[crokey::crossterm::style::Attribute]&gt;&gt;
             &lt;crokey::crossterm::style::Attributes as std::convert::From&lt;crokey::crossterm::style::Attribute&gt;&gt;
   = note: required because of the requirements on the impl of `Into&lt;crokey::crossterm::style::Attributes&gt;` for `crossterm::style::Attribute`

error[E0308]: arguments to this function are incorrect
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\state.rs:62:14
   |
62 |             .set_fgbg(AnsiValue(252), AnsiValue(239));
   |              ^^^^^^^^ --------------  -------------- expected enum `crokey::crossterm::style::Color`, found enum `crossterm::style::Color`
   |                       |
   |                       expected enum `crokey::crossterm::style::Color`, found enum `crossterm::style::Color`
   |
   = note: perhaps two different versions of crate `crossterm` are being used?
   = note: perhaps two different versions of crate `crossterm` are being used?
note: associated function defined here
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\termimad-0.20.2\src\line_style.rs:33:12
   |
33 |     pub fn set_fgbg(&amp;mut self, fg: Color, bg: Color) {
   |            ^^^^^^^^

error[E0308]: mismatched types
   --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\state.rs:63:54
    |
63  |         status_skin.italic = CompoundStyle::new(Some(AnsiValue(204)), None, Attribute::Bold.into());
    |                                                 ---- ^^^^^^^^^^^^^^ expected enum `crokey::crossterm::style::Color`, found enum `crossterm::style::Color`
    |                                                 |
    |                                                 arguments to this enum variant are incorrect
    |
    = note: perhaps two different versions of crate `crossterm` are being used?
note: tuple variant defined here
   --&gt; C:\Users\------\.rustup\toolchains\stable-x86_64-pc-windows-msvc\lib/rustlib/src/rust\library\core\src\option.rs:526:5
    |
526 |     Some(#[stable(feature = &quot;rust1&quot;, since = &quot;1.0.0&quot;)] T),
    |     ^^^^

error[E0277]: the trait bound `crokey::crossterm::style::Attributes: std::convert::From&lt;crossterm::style::Attribute&gt;` is not satisfied
  --&gt; C:\Users\------\.cargo\registry\src\github.com-1ecc6299db9ec823\bacon-2.2.0\src\state.rs:63:93
   |
63 |         status_skin.italic = CompoundStyle::new(Some(AnsiValue(204)), None, Attribute::Bold.into());
   |                                                                                             ^^^^ the trait `std::convert::From&lt;crossterm::style::Attribute&gt;` is not implemented for `crokey::crossterm::style::Attributes`
   |
   = help: the following other types implement trait `std::convert::From&lt;T&gt;`:
             &lt;crokey::crossterm::style::Attributes as std::convert::From&lt;&amp;[crokey::crossterm::style::Attribute]&gt;&gt;
             &lt;crokey::crossterm::style::Attributes as std::convert::From&lt;crokey::crossterm::style::Attribute&gt;&gt;
   = note: required because of the requirements on the impl of `Into&lt;crokey::crossterm::style::Attributes&gt;` for `crossterm::style::Attribute`

Some errors have detailed explanations: E0277, E0308, E0599.
For more information about an error, try `rustc --explain E0277`.
error: could not compile `bacon` due to 10 previous errors
</pre>
</details>

**Comment by Stargateur** [comment]
enable_io is quite weird cause you can have it by activate net feature of tokio.

**Comment by Canop** [comment]
@Fluhzar  Can you please confirm that the fix works for you (it's on main but not yet in crates.io)

**Comment by Fluhzar** [comment]
@Canop Yup, compiles and installs now, thank you!
