### ISSUE TITLE
configuration file : user feedback needed

### ISSUE THREAD

**Issue by Canop** [Canop/bacon#9]
There will be a few things to configure, most notably the options to add to `cargo watch` or `cargo test` for the default bacon launch in the project.

Right now the idea is to have a `bacon.toml` file in the project's dir but I'd like to have opinions about that.

**Comment by jyn514** [comment]
I'd like to set a base command other than `cargo` (`x.py`, for the rust compiler).

**Comment by jyn514** [comment]
Also, x.py doesn't support `--color always`, but maybe I should just fix that upstream.

**Comment by jyn514** [comment]
> Right now the idea is to have a bacon.toml file in the project's dir but I'd like to have opinions about that.

Another option is to make the configuration part of `Cargo.toml` directly, the way docs.rs does it: https://docs.rs/about/metadata. But I don't have strong opinions on whether that's better or worse than `bacon.toml`.

**Comment by jyn514** [comment]
I'd also like to set summary mode on by default. Right now it's opt-in with `s`, but I rarely want to see the whole error the first time I start up bacon.

**Comment by Canop** [comment]
The `bacon.toml` file is expected to look like this:

```
default_job = "check"

[jobs]

[jobs.check]
command = "cargo check --color always"

[jobs.check_windows]
command = "cargo check --target x86_64-pc-windows-gnu --color always"

[jobs.clippy]
command = "cargo clippy --color always"

[jobs.tests]
key = "t"
command = "cargo test --color always"
```

**Comment by Canop** [comment]
I've still not decided for

    command = "cargo check --target x86_64-pc-windows-gnu --color always"

or

    command = ["cargo", "check", "--target", "x86_64-pc-windows-gnu", "--color", "always"]

The latter is more powerful but so painful to type in common cases...

**Comment by jyn514** [comment]
I'd prefer the second version, I don't expect many people to use the configuration file so it's ok to make it a little harder to write.
