### ISSUE TITLE
Disable watch feature for custom job

### ISSUE THREAD

**Issue by nfedyashev** [Canop/bacon#92]
Is it possible to disable `watch` feature for a job? I've tried setting it to `[]`(or removing completely) but it seems to didn't have any effect for my custom job because it is still triggered on any file update.

My use case is the following:
I wanted to focus on a specific test that has some side effects and I wanted it to be triggered only on keybinding press and not on file updates.

Any hints are greatly appreciated.

**Comment by Canop** [comment]
This is not possible today because I didn't think about such use-case.

I see two possible ergonomics:

* a setting on the job to disable watching
* a key which would toggle watching on/off, usable on any job

**Comment by nfedyashev** [comment]
Thank you!
I think I've found a workaround that seems to work fine.

```
 bacon --job test-focus --path ./blankfolder
```
