### ISSUE TITLE
Passing the `--test-threads` flag not working

### ISSUE THREAD

**Issue by JoelMon** [Canop/bacon#93]
Hello,

Ran into an issue while running `bacon test -- --test-threads=1`. I was expecting to have bacon run the tests using only a single thread. 

Not sure if it's possible to do this or if there's a bug.

## System
- PopOS Linux
- bacon 2.2.5

Thanks

**Comment by Canop** [comment]
This should be possible (never tested it).
Can you please test with `bacon test -- -- --test-threads=1` as `cargo test` already need a `--` ?

**Comment by Canop** [comment]
I've looked into it a little and don't find any better way than to avoid /proc. I'll hardcode it.

**Comment by Canop** [comment]
Thanks for the confirmation. I'll add that to the documentation.

**Comment by Canop** [comment]
Done: https://dystroy.org/bacon/cookbook/#variable-arguments
