### ISSUE TITLE
`bacon run` doesn't work with the default settings in projects with multiple binaries

### ISSUE THREAD

**Issue by rdvdev2** [Canop/bacon#96]
The issue is introduced with this [change](https://github.com/Canop/bacon/commit/844e936ff31e21407596173cecaf5026ef4fd9bd#diff-571a61e4e3bb8f8b9a783e8b396f4c1611dcc3a8233cb5988fd02c87e3a970da).

Before the change, I could run a project with multiple binaries with `bacon run -- --bin=BINARY_NAME`. However, with the additional `--` that was added to the default settings, this is no longer possible, as arguments are directly passed to the program and not cargo. This is fairly counterintuitive, and I couldn't discover why I could no longer run my project until I generated a config file.

I think that reverting the change will be more user-friendly, as it allows running the program without configuration files (if one desires to do so) and it is more consistent with the behavior of similar jobs like `test`.

**Comment by Canop** [comment]
> I think that reverting the change will be more user-friendly, as it allows running the program without configuration files (if one desires to do so) and it is more consistent with the behavior of similar jobs like test.

You're right. Adding this `--` was a bad decision.
